### ISSUE TITLE
Setting UseEnvironmentFonts to false does not skip loading of default fonts

### ISSUE THREAD

**Issue by jscarle** [QuestPDF/QuestPDF#1017]
**Describe the bug**

Setting `QuestPdf.Settings.UseEnvironmentFonts` to `false` does not skip loading of default fonts, which can cause hard to diagnose issues.

**To Reproduce**
Set `QuestPdf.Settings.UseEnvironmentFonts` to `false`, then load a .NET application from a path with subfolders that are inaccessible to the application.

**Expected behavior**
Setting `QuestPdf.Settings.UseEnvironmentFonts` to `false` should skip `RegisterLibraryDefaultFonts()` in `FontManager` (See [source](https://github.com/QuestPDF/QuestPDF/blob/ae30cb76f8ffa886d2f1dba7c28cefb33c565c81/Source/QuestPDF/Drawing/FontManager.cs#L26C13-L26C43)).

**Screenshots**
N/A

**Environment**
v2024.10.0
Linux Docker Image

**Additional context**
If loading the .NET application from the root of a docker image, a stack trace similar to this one will be produced, regardless of any settings applied:

```
System.TypeInitializationException: The type initializer for 'QuestPDF.Drawing.FontManager' threw an exception.
---> System.UnauthorizedAccessException: Access to the path '/proc/tty/driver' is denied.
---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.DequeueNextDirectory()
   at System.IO.Enumeration.FileSystemEnumerator`1.DirectoryFinished()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.ToList()
   at QuestPDF.Drawing.FontManager.<RegisterLibraryDefaultFonts>g__SearchFontFiles|10_0()
   at QuestPDF.Drawing.FontManager.RegisterLibraryDefaultFonts()
   at QuestPDF.Drawing.FontManager..cctor()
   --- End of inner exception stack trace ---
   at QuestPDF.Drawing.FontManager.get_TypefaceProvider()
   at QuestPDF.Elements.Text.SkParagraphBuilderPoolManager.Get(ParagraphStyleConfiguration configuration)
   at QuestPDF.Elements.Text.TextBlock.BuildParagraph()
   at QuestPDF.Elements.Text.TextBlock.Initialize()
   at QuestPDF.Elements.Text.TextBlock.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Padding.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Extend.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Extend.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Decoration.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Decoration.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Padding.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Constrained.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Layers.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.SnapshotRecorder.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, ContainerElement content)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(SkWriteStream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
```

**Comment by MarcinZiabek** [comment]
Thank you for reporting this issue 😄 

It should be fixed in the latest `2024.10.1` release. Could you please try it?

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by jscarle** [comment]
All goo, thanks
