### ISSUE TITLE
Companion App cannot render merged document

### ISSUE THREAD

**Issue by akselkvitberg** [QuestPDF/QuestPDF#1019]
**Is your feature request related to a problem? Please describe.**
If I merge several documents together, the companion app crashes with the following exception:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at QuestPDF.Companion.CompanionModelHelpers.<ImproveHierarchyStructure>g__FindDebugPointers|3_2(DocumentHierarchyElement element, <>c__DisplayClass3_0&)
   at QuestPDF.Companion.CompanionModelHelpers.ImproveHierarchyStructure(DocumentHierarchyElement root)
   at QuestPDF.Companion.CompanionService.RefreshPreview(CompanionDocumentSnapshot companionDocumentSnapshot)
   at QuestPDF.Companion.CompanionExtensions.ShowInCompanionAsync(IDocument document, Int32 port, CancellationToken cancellationToken)
   at QuestPDF.Companion.CompanionExtensions.ShowInCompanion(IDocument document, Int32 port)

```

The problem seems to be with `DocumentGenerator.cs` where `RenderSingleDocument` checks to see if canvas is CompanionCanvas, and sets Hierarchy if that is the case. `RenderMergedDocument` does not check for CompanionCanvas and does not set Hierarchy.

**Describe the solution you'd like**
RenderMergedDocument should set Hierarchy if canvas is a CompanionCanvas.

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by MarcinZiabek** [comment]
Since there has been no recent activity, I’m closing this issue. If you experience a similar problem or have a related request, feel free to open a new GitHub issue. I appreciate your feedback! ❤️
