### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by huang858563** [QuestPDF/QuestPDF#1043]
at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuestPDF.Drawing.DocumentGenerator.<RenderPass>g__GenerateLayoutExceptionDebuggingInfo|11_3[TCanvas](<>c__DisplayClass11_0`1& )
   at QuestPDF.Drawing.DocumentGenerator.<RenderPass>g__ThrowLayoutException|11_2[TCanvas](<>c__DisplayClass11_0`1& )
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, ContainerElement content)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(SkWriteStream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at QuestPDFDemo.Program.Main(String[] args) in Program.cs:line 18

![exception](https://github.com/user-attachments/assets/17c4adec-1997-4be6-b179-083b49902175)

**Comment by pennellarodrigo** [comment]
I'm encountering the same error, but my layout is much more complex, and I'm struggling to identify the problem.

**Comment by erobsodev** [comment]
I was struggling with this earlier today. Upgrading to 2024.10.3 seems to have improved the layout error reporting, enabling me to at least locate the elements having trouble.
