### ISSUE TITLE
Can not use image at layers

### ISSUE THREAD

**Issue by mustafaunall** [QuestPDF/QuestPDF#1051]
I have an exception at below when trying to use image method into the layers method. I am using **.net 8 webapi** and **docker compose**, i installed these packages:
QuestPDF - 2024.7.3
QuestPDF.Markdown - 1.21.0
HarfBuzzSharp - 7.3.0.3
HarfBuzzSharp.NativeAssets.Linux - 7.3.0.3
SkiaSharp - 2.88.9
SkiaSharp.NativeAssets.Linux.NoDependencies - 2.88.9

In example look at the exception below, i think i am using the right way but i have an exception.
Exception details:
Cannot decode the provided image.QuestPDF.Drawing.Exceptions.DocumentComposeException: Cannot decode the provided image.
at QuestPDF.Infrastructure.Image.DecodeImage(SkData imageData)
at QuestPDF.Infrastructure.Image.FromFile(String filePath)
at QuestPDF.Fluent.ImageExtensions.Image(IContainer parent, String filePath)
at QuestPDF.Fluent.ImageExtensions.Image(IContainer parent, String filePath, ImageScaling scaling)

I tried two types of approach, i need your help.

First approach:

```cs
using Core.Domain.ViewModel.Report;
using Core.Helpers;

using SkiaSharp;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Core.Service.PdfDocuments.Pages.ReportDocument;

public class Page1(ReportExportVm model)
{
    public ReportExportVm Model { get; } = model;

    public void Compose(PageDescriptor page)
    {
        var coverNewAsset =
            Path.GetFullPath(Path.Combine(OsHelper.GetPdfAssetsPath(), "ReportDocument", "cover_full.png"));

        page.Size(PageSizes.A4.Portrait());
        page.PageColor(Colors.White);
        page.DefaultTextStyle(x => x.FontSize(12));
        page.DefaultTextStyle(x => x.FontFamily("Calibri"));

        page.Header();

        page.Content().Container()
            .Layers(l =>
            {
                l.PrimaryLayer().Padding(0).Image(coverNewAsset, ImageScaling.Resize);
                l.Layer()
                    .Column(column =>
                    {
                        column.Item()
                            .PaddingLeft(4f, Unit.Centimetre)
                            .PaddingTop(4.70f, Unit.Centimetre)
                            .Text(model.TestDate.ToString("dd.MM.yyyy"))
                            .FontSize(14)
                            .FontColor(Colors.White);
                    });
                l.Layer()
                    .AlignCenter()
                    .AlignMiddle()
                    .Row(r =>
                    {
                        r.AutoItem().PaddingTop(1).PaddingLeft(120)
                            .Column(cr =>
                            {
                                cr.Item().MaxWidth(240).Text(Model.CompanyName)
                                    .FontSize(34).ExtraBold();
                                cr.Item().PaddingTop(10).Text(Model.ReportName).FontSize(18).Bold();
                                cr.Item().PaddingTop(10).Text("Report Date:").FontSize(16);
                                cr.Item().PaddingTop(10)
                                    .Text($"{Model.ReportStartDate:dd.MM.yyyy} - {Model.ReportEndDate:dd.MM.yyyy}")
                                    .FontSize(16);
                            });
                    });
            });
   
    
        
    }

}

```

Second approach:

```cs
using Core.Domain.ViewModel.Report;
using Core.Helpers;
using SkiaSharp;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Core.Service.PdfDocuments.Pages.ReportDocument;

public class Page1(ReportExportVm model)
{
    public ReportExportVm Model { get; } = model;

    public void Compose(PageDescriptor page)
    {
        page.Size(PageSizes.A4.Portrait());
        page.PageColor(Colors.White);
        page.DefaultTextStyle(x => x.FontSize(12));
        page.DefaultTextStyle(x => x.FontFamily("Calibri"));

        page.Header();

        page.Content().Container()
            .Layers(l =>
            {
                try
                {
                    var coverNewAsset =
                        Path.GetFullPath(Path.Combine(OsHelper.GetPdfAssetsPath(), "ReportDocument", "cover_full2.png"));
                    
                    using var stream = File.OpenRead(coverNewAsset);
                    using var codec = SKCodec.Create(stream);

                    if (codec == null)
                    {
                        throw new InvalidOperationException(
                            "SKCodec could not read the file. The file format may not be supported or the file may be corrupt.");
                    }

                    using var bitmap = SKBitmap.Decode(codec);
                    if (bitmap == null)
                    {
                        throw new InvalidOperationException("SKBitmap decode operation failed.");
                    }

                    using var image = SKImage.FromBitmap(bitmap);
                    using var data = image.Encode(SKEncodedImageFormat.Png, 100);

                    using var memoryStream = new MemoryStream();
                    data.SaveTo(memoryStream);
                    memoryStream.Seek(0, SeekOrigin.Begin);

                    l.PrimaryLayer().Padding(0).Image(memoryStream, ImageScaling.FitArea);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("An error occurred during decode: " + ex.Message);
                }

                l.Layer()
                    .Column(column =>
                    {
                        column.Item()
                            .PaddingLeft(4f, Unit.Centimetre)
                            .PaddingTop(4.70f, Unit.Centimetre)
                            .Text(model.TestDate.ToString("dd.MM.yyyy"))
                            .FontSize(14)
                            .FontColor(Colors.White);
                    });

                l.Layer()
                    .AlignCenter()
                    .AlignMiddle()
                    .Row(r =>
                    {
                        r.AutoItem().PaddingTop(1).PaddingLeft(120)
                            .Column(cr =>
                            {
                                cr.Item().MaxWidth(240).Text(Model.CompanyName)
                                    .FontSize(34).ExtraBold();
                                cr.Item().PaddingTop(10).Text(Model.ReportName).FontSize(18).Bold();
                                cr.Item().PaddingTop(10).Text("Report Date:").FontSize(16);
                                cr.Item().PaddingTop(10)
                                    .Text($"{Model.ReportStartDate:dd.MM.yyyy} - {Model.ReportEndDate:dd.MM.yyyy}")
                                    .FontSize(16);
                            });
                    });
            });
    }
}
```

**Comment by OnurDogan-RSU** [comment]
I have the same issue. It would be great if there is a solution.

**Comment by enesberk** [comment]
I have the same problem. It would be great to have a solution for this.

**Comment by SefaDudu** [comment]
Hi i have the same issue. ,  it works for me local but  the server gives an error.

**Comment by mustafaunall** [comment]
> Hi Mustafa, I used svg instead of image and my error is solved. I fixed your code please try this.
> 
> public void Compose(PageDescriptor page) { page.Size(PageSizes.A4.Portrait()); page.PageColor(Colors.White); page.DefaultTextStyle(x => x.FontSize(12)); page.DefaultTextStyle(x => x.FontFamily("Calibri"));
> 
> ```
>     var coverNewAsset =
>         Path.GetFullPath(Path.Combine(OsHelper.GetPdfAssetsPath(), "RsuReportDocument", "cover_full.svg"));
>     var image = SvgImage.FromFile(coverNewAsset);
>     page.Background().Svg(image).FitArea();
> 
>     page.Content()
>         .Padding(0)
>         .Layers(l =>
>         {
>             l.PrimaryLayer()
>                 .Column(column =>
>                 {
>                     column.Item()
>                         .PaddingLeft(4f, Unit.Centimetre)
>                         .PaddingTop(4.70f, Unit.Centimetre)
>                         .Text(model.TestDate.ToString("dd.MM.yyyy"))
>                         .FontSize(14)
>                         .FontColor(Colors.White);
>                 });
> 
>             l.Layer()
>                 .AlignCenter()
>                 .AlignMiddle()
>                 .Row(r =>
>                 {
>                     r.AutoItem().PaddingTop(1).PaddingLeft(120)
>                         .Column(cr =>
>                         {
>                             cr.Item().MaxWidth(240).Text(Model.CompanyName)
>                                 .FontSize(34).ExtraBold();
>                             cr.Item().PaddingTop(10).Text(Model.ReportName).FontSize(18).Bold();
>                             cr.Item().PaddingTop(10).Text("Report Date:").FontSize(16);
>                             cr.Item().PaddingTop(10)
>                                 .Text($"{Model.ReportStartDate:dd.MM.yyyy} - {Model.ReportEndDate:dd.MM.yyyy}")
>                                 .FontSize(16);
>                         });
>                 });
>         });
> }
> ```

Only one layer background unfortunately did not solve my situation when I tried this code, I need to use more than one layer. But thanks anyway

**Comment by MarcinZiabek** [comment]
It looks like the issue originates in Skia’s decoding logic. Your image files may be partially corrupted or using an uncommon, unsupported setting. I recommend opening the file in a graphics editor (e.g., GIMP) and resaving it to see if that resolves the problem.

Since there has been no recent activity, I’m closing this issue. If you have a similar request in the future, feel free to open a new GitHub issue. Thanks for your feedback! ❤️
