### ISSUE TITLE
Unable to generate XPS Documents on Linux

### ISSUE THREAD

**Issue by moorbren** [QuestPDF/QuestPDF#1063]
**Describe the bug**
Running `document.GenerateXPS()` results in the following error message when run on Linux. I have no issues generating PDFs via `document.GeneratePDF()`. The XPS generation works fine on Windows. 

**To Reproduce**
Just call it on a Linux machine. Haven't tested on any other Linux machines.

**Expected behavior**
This function should generate the XPS document like it does on Windows...

**Screenshots**
See additional context.

**Environment**

*What version of the library do you use?*
Running QuestPDF v2024.10.4.

Here is my full dependency list for QuestPDF and the other Linux related dependencies:
``` XML
    <!-- svg skia for using SVGs inside QuestPDF -->
    <PackageReference Include="QuestPDF" Version="2024.10.4" />
    <PackageReference Include="Svg.Skia" Version="2.0.0.2" />
    <!-- For running QuestPDF on Linux -->
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies"
      Version="3.118.0-preview.1.2" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1-preview.1.2" />

    <PackageReference Include="RazorEngineCore" Version="2024.4.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="RazorLight" Version="2.3.1" />
```

What operating system do you use? (OS type, x64 vs x86 vs arm64)
Encountering this issue on an Azure App Service. Running 64-bit Linux on x86_64 architecture: 
```bash
uname -a
> Linux host_c62ad9d17b 5.15.0-1031-azure #36~20.04.1-Ubuntu SMP Wed Sep 7 19:09:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
>   PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
    NAME="Debian GNU/Linux"
    VERSION_ID="12"
    VERSION="12 (bookworm)"
    VERSION_CODENAME=bookworm
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
    root@host_c62ad9d17b:~/site/wwwroot#
```

**Additional context**
The specific error message:
```bash
A Global Error Occurred, got exception: Unable to find an entry point named 'xps_document_create' in shared library 'QuestPdfSkia'., Stack =    at QuestPDF.Skia.SkXpsDocument.API.xps_document_create(IntPtr stream, Single dpi)
  at QuestPDF.Skia.SkXpsDocument.Create(SkWriteStream stream, Single dpi)
  at QuestPDF.Drawing.XpsCanvas.CreateXps(SkWriteStream stream, DocumentSettings documentSettings)
  at QuestPDF.Drawing.XpsCanvas..ctor(SkWriteStream stream, DocumentSettings documentSettings)
  at QuestPDF.Drawing.DocumentGenerator.GenerateXps(SkWriteStream stream, IDocument document)
  at QuestPDF.Fluent.GenerateExtensions.GenerateXps(IDocument document)
  at Project.API.Controllers.PrinterController.GetPickTicketReportXps(Int64 orderId) in /builds/<redacted>/Controllers/PrinterController.cs.cs:line 145
  at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

**Comment by MarcinZiabek** [comment]
I apologise for the late reply.

Unfortunately, XPS generation is supported only on Windows. QuestPDF relies on Skia's XPS backend, which is implemented on top of the native Windows XPS Document API. There is no cross-platform implementation, so this limitation cannot be lifted on the library side.

Since you reported this issue, we have improved the behavior: calling GenerateXps() on a non-Windows platform now throws a clear exception describing this limitation, instead of failing with a cryptic native error.
