### ISSUE TITLE
DocumentOperation MergeFile not working in Docker Asp.NET 8 on version 2024.12.0

### ISSUE THREAD

**Issue by mdvaras** [QuestPDF/QuestPDF#1076]
When working with version 2024.12.0 **MergeFile works well** when run directly in VisualStudio using Kestrel. 
When the same code is started using Docker container built with mcr.microsoft.com/dotnet/aspnet:8.0, error below occurs.

I tried to mitigate the problem by installation of qpdf that seems to be the issue, but that did no help:

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    qpdf 
``` 

**Error message**
The QuestPDF library has encountered an issue while loading one of its dependencies.
Your runtime is currently not supported by QuestPDF. Currently supported runtimes are: win-x86, win-x64, linux-x64, linux-arm64, linux-musl-x64, osx-x64, osx-arm64. 
It appears that your current operating system distribution may be outdated. For optimal compatibility, please consider updating it to a more recent version.

**Error details**
Unable to load shared library 'qpdf' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/app/bin/Debug/net8.0/runtimes/linux-x64/native/qpdf.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/qpdf.so: cannot open shared object file: No such file or directory
libjpeg.so.8: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/runtimes/linux-x64/native/qpdf: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/qpdf: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/runtimes/linux-x64/native/libqpdf: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/libqpdf: cannot open shared object file: No such file or directory

**Comment by MarcinZiabek** [comment]
The library should provide you with a detailed list of dependencies to install. I will investigate why it did not happen.

For linux: `apt install openssl-bin gnutls-bin libjpeg-dev`
For linux musl: `apk add openssl gnutls libjpeg-turbo`

Please also ensure that the OpenSSL library is installed on your system with a version at least 3.0.0.

Could you please try the above and let me know if it fixes the problem? Please do NOT install the qpdf package.

**Comment by mdvaras** [comment]
Hi Marcin,
I am sorry for asking, but can you point me to the place where: "The library should provide you with a detailed list of dependencies to install." ? I could not find such list on this github in your code. I will be happy to try other libraries.

As for your recommendation:
openssl was already installed in ver. 3.0.15-1~deb12u1
gnutls-bin was added, now in ver. 3.7.9-2+deb12u3
libjpeg-dev was added, now in ver. 1:2.1.5-2

The problem is the same - very same error message.

**Comment by mdvaras** [comment]
Hi Marcin,
before I give up, I want to try again and ask you if there is some list of other libraries I could try on Docker container built on mcr.microsoft.com/dotnet/aspnet:8.0. I tried your newest version 2024.12.1 and I followed error instructions as I did before. Even though I installed missing libraries, the result is the same like in my first post.  
Thank you, Martin

**Comment by girlpunk** [comment]
Hi, Are you able to confirm what system architecture your container is running in?

**Comment by mdvaras** [comment]
Hi, thanks a lot for trying to help here. I am pretty sure that container is within the spec from Marcin. I just think that there is missing some library since 2 out of 3 that Marcin mention were not there (see above). I think there might be some more missing, and I tried to search Marcin's code like Source/QuestPDF/QuestPDF.csproj, but could not find any listing to try.

Here is requested info:
`docker exec -it contTest dotnet --info`

```
Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3
  RID:          linux-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None
```

Similar for `docker image inspect`:
```
"Architecture": "amd64",
"Os": "linux",
```

**Comment by MarcinZiabek** [comment]
The native build is created and tested on the  `ubuntu:18.04` docker image, and then further tested with `ubuntu:24.04`. Let me investigate `mcr.microsoft.com/dotnet/aspnet:8.0` to learn what could be missing.

@mdvaras Could you please share the exact exception message? Please ensure to include the inner exception, as it may contain valuable details.

**Comment by mdvaras** [comment]
@MarcinZiabek As requested, I am attaching all I could find and looked reasonable:
```
((System.TypeLoadException)ex.InnerException).Message
	Unable to load shared library 'qpdf' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
	/app/bin/Debug/net8.0/runtimes/linux-x64/native/qpdf.so: cannot open shared object file: No such file or directory
	/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf.so: cannot open shared object file: No such file or directory
	/app/bin/Debug/net8.0/qpdf.so: cannot open shared object file: No such file or directory
	libjpeg.so.8: cannot open shared object file: No such file or directory
	/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf.so: cannot open shared object file: No such file or directory
	/app/bin/Debug/net8.0/runtimes/linux-x64/native/qpdf: cannot open shared object file: No such file or directory
	/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf: cannot open shared object file: No such file or directory
	/app/bin/Debug/net8.0/qpdf: cannot open shared object file: No such file or directory
	/app/bin/Debug/net8.0/runtimes/linux-x64/native/libqpdf: cannot open shared object file: No such file or directory
	/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf: cannot open shared object file: No such file or directory
	/app/bin/Debug/net8.0/libqpdf: cannot open shared object file: No such file or directory

ex.InnerException.SerializationStackTraceString
   at QuestPDF.Qpdf.QpdfAPI.API.qpdf_get_qpdf_version()
   at QuestPDF.Qpdf.QpdfAPI.GetQpdfVersion()
   at QuestPDF.Qpdf.QpdfNativeDependencyCompatibilityChecker.ExecuteNativeCode()
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.CheckIfExceptionIsThrownWhenLoadingNativeDependencies()
   
ex.Message
	The QuestPDF library has encountered an issue while loading one of its dependencies.
	Your runtime is currently not supported by QuestPDF. Currently supported runtimes are: win-x86, win-x64, linux-x64, linux-arm64, linux-musl-x64, osx-x64, osx-arm64. 
	It appears that your current operating system distribution may be outdated. For optimal compatibility, please consider updating it to a more recent version.
	System.Func`1[System.String]
	
ex.StackTrace
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.<TestOnce>g__ThrowCompatibilityException|13_0(Exception innerException)
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.TestOnce()
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.Test()
   at QuestPDF.Qpdf.QpdfNativeDependencyCompatibilityChecker.Test()
   at QuestPDF.Qpdf.QpdfAPI.ExecuteJob(String jobJson)
   at QuestPDF.Fluent.DocumentOperation.Save(String filePath)
   at Test.Reports.ReportService.MergeTwoPdfFiles(String firstFilePathAndName, String secondFilePathAndName) in ReportService.cs:line 85
```

**Comment by wangyuxinfirst** [comment]
Having similar issue on Mac Pro M2 OS Sonoma. It works in Windows.
It looks like qpdf.dylib is missing.

`Exception has occurred: CLR/System.Exception
* 
Exception thrown: 'System.Exception' in QuestPDF.dll: 'The QuestPDF library has encountered an issue while loading one of its dependencies.

Your runtime is currently not supported by QuestPDF. Currently supported runtimes are: win-x86, win-x64, linux-x64, linux-arm64, linux-musl-x64, osx-x64, osx-arm64. 

It appears that your current operating system distribution may be outdated. For optimal compatibility, please consider updating it to a more recent version.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.DllNotFoundException : Unable to load shared library 'qpdf' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf.dylib, 0x0001): tried: '/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf.dylib' (no such file), '/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf.dylib' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf.dylib' (no such file)
dlopen(/...Api/bin/Debug/net8.0/qpdf.dylib, 0x0001): tried: '/...Api/bin/Debug/net8.0/qpdf.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/...Api/bin/Debug/net8.0/qpdf.dylib' (no such file), '/...Api/bin/Debug/net8.0/qpdf.dylib' (no such file)
dlopen(qpdf.dylib, 0x0001): tried: 'qpdf.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSqpdf.dylib' (no such file), '/usr/lib/qpdf.dylib' (no such file, not in dyld cache), 'qpdf.dylib' (no such file), '/usr/local/lib/qpdf.dylib' (no such file), '/usr/lib/qpdf.dylib' (no such file, not in dyld cache)
dlopen(/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/libqpdf.dylib, 0x0001): Library not loaded: /opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib
  Referenced from: <8A28426D-7E0A-332A-AA5C-CEE59CB08DA2> /...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/libqpdf.dylib
  Reason: tried: '/opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib' (no such file), '/opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf.dylib' (no such file)
dlopen(/...Api/bin/Debug/net8.0/libqpdf.dylib, 0x0001): Library not loaded: /opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib
  Referenced from: <8A28426D-7E0A-332A-AA5C-CEE59CB08DA2> /...Api/bin/Debug/net8.0/libqpdf.dylib
  Reason: tried: '/opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib' (no such file), '/opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib' (no such file)
dlopen(libqpdf.dylib, 0x0001): tried: 'libqpdf.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibqpdf.dylib' (no such file), '/usr/lib/libqpdf.dylib' (no such file, not in dyld cache), 'libqpdf.dylib' (no such file), '/usr/local/lib/libqpdf.dylib' (no such file), '/usr/lib/libqpdf.dylib' (no such file, not in dyld cache)
dlopen(/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf, 0x0001): tried: '/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf' (no such file), '/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/qpdf' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/qpdf' (no such file)
dlopen(/...Api/bin/Debug/net8.0/qpdf, 0x0001): tried: '/...Api/bin/Debug/net8.0/qpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/...Api/bin/Debug/net8.0/qpdf' (no such file), '/...Api/bin/Debug/net8.0/qpdf' (no such file)
dlopen(qpdf, 0x0001): tried: 'qpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OSqpdf' (no such file), '/usr/lib/qpdf' (no such file, not in dyld cache), 'qpdf' (no such file), '/usr/local/lib/qpdf' (no such file), '/usr/lib/qpdf' (no such file, not in dyld cache)
dlopen(/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/libqpdf, 0x0001): tried: '/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/libqpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/libqpdf' (no such file), '/...Api/bin/Debug/net8.0/runtimes/osx-arm64/native/libqpdf' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libqpdf' (no such file)
dlopen(/...Api/bin/Debug/net8.0/libqpdf, 0x0001): tried: '/...Api/bin/Debug/net8.0/libqpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/...Api/bin/Debug/net8.0/libqpdf' (no such file), '/...Api/bin/Debug/net8.0/libqpdf' (no such file)
dlopen(libqpdf, 0x0001): tried: 'libqpdf' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibqpdf' (no such file), '/usr/lib/libqpdf' (no such file, not in dyld cache), 'libqpdf' (no such file), '/usr/local/lib/libqpdf' (no such file), '/usr/lib/libqpdf' (no such file, not in dyld cache)
   at QuestPDF.Qpdf.QpdfAPI.API.qpdf_get_qpdf_version()
   at QuestPDF.Qpdf.QpdfAPI.GetQpdfVersion()
   at QuestPDF.Qpdf.QpdfNativeDependencyCompatibilityChecker.ExecuteNativeCode()
   at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.CheckIfExceptionIsThrownWhenLoadingNativeDependencies()
`

**Comment by wangyuxinfirst** [comment]
figured out in mac. I need to:
brew install gnutls

**Comment by KronerPa** [comment]
Hey guys,
it seems that i have some similar issues related to merge documents in a docker.
As the error messages suggested i installed openssl and  libjpeg-turbo, but it aint working out.

To resolve the loading errors i tried to load the libqpdf library and got the following result:

`ubuntu-8gb-nbg1-1:/# docker exec -it con ldd /app/libqpdf.so
        linux-vdso.so.1 (0x0000f69c58c38000)
        libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000f69c58bc0000)
        libjpeg.so.8 => not found
        libcrypto.so.3 => /lib/aarch64-linux-gnu/libcrypto.so.3 (0x0000f69c58200000)
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000f69c57e00000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000f69c58b80000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000f69c58050000)
        /lib/ld-linux-aarch64.so.1 (0x0000f69c58bfb000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000f69c58760000)`

I would've figured that installing libjpeg-turbo should lead to a loadable libjpeg, but yeah.
Any help is appreciated.

**Comment by MarcinZiabek** [comment]
@KronerPa  Could you please try with at least `2024.12.3` version? 

I am testing compatibility with docker ubuntu:24.04 and command `apt install openssl libjpeg-turbo8 --yes`. https://github.com/QuestPDF/QuestPDF/blob/main/.github/workflows/main.yml

**Comment by KronerPa** [comment]
@MarcinZiabek Thanks for the fast reply. I tried it with 2025.1.1 and 2024.12.3 now.

The behavior is for both version identical.

**Comment by KronerPa** [comment]
@MarcinZiabek  is there anything else i can check to investigate further? Which libraries should be passed on after build in the runtime folder for example?

**Comment by KronerPa** [comment]
@MarcinZiabek on my side the Release of 2025.1.2 fixes the deployment problems and it's possible to merge files again 👍 

Thanks for the support.

**Comment by MarcinZiabek** [comment]
It appears that this problem has been successfully resolved.

Since there has been no recent activity, I’m closing this issue. If you have a similar request in the future, please feel free to open a new GitHub issue. Thanks for your feedback! ❤️

**Comment by mdvaras** [comment]
Marcin, I cannot test your fix yet as I have workaround implemented in production version, but I just want to say thanks for all the work you do. QuestPDF is awesome.
