### ISSUE TITLE
DocumentDrawingException when Page Break occurs exactly before next Table-Item

### ISSUE THREAD

**Issue by RobertK66** [QuestPDF/QuestPDF#1084]
While refactoring my working document, I added an extra PaddingBottom(10) to my header. That triggered a DocumentDrawingException:
```
QuestPDF.Drawing.Exceptions.DocumentDrawingException
  HResult=0x80131500
  Message=An exception occured during document drawing.
  Source=QuestPDF
  StackTrace:
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, ContainerElement content)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(SkWriteStream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at Cli_Access.....CreatePdf(String bpath) in D:...2.cs:line 148
   at Cli_Access.Program.RunIt() in D:....\Program.cs:line 65
   at Cli_Access.Program.Main(String[] args) in D:...\Program.cs:line 39

  This exception was originally thrown at this call stack:
    QuestPDF.Skia.SkiaAPI.EnsureNotNull(nint)
    QuestPDF.Skia.SkImage.SkImage(nint)
    QuestPDF.Skia.SkImage.ResizeAndCompress(int, int, int, bool)
    QuestPDF.Helpers.Helpers.ResizeAndCompressImage(QuestPDF.Skia.SkImage, QuestPDF.Infrastructure.ImageSize, QuestPDF.Infrastructure.ImageCompressionQuality)
    QuestPDF.Infrastructure.Image.GetVersionOfSize(QuestPDF.Infrastructure.GetImageVersionRequest)
    QuestPDF.Elements.Image.GetImageToDraw(QuestPDF.Infrastructure.Size)
    QuestPDF.Elements.Image.Draw(QuestPDF.Infrastructure.Size)
    QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size)
    QuestPDF.Elements.AspectRatio.Draw(QuestPDF.Infrastructure.Size)
    QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size)
    ...
    [Call Stack Truncated]

Inner Exception 1:
InitializationException: QuestPDF cannot instantiate native object.
```

After some playing around I was able to pin down the problem to be a random thing when a Page break exactly hits between a Text and a Table Item. 

See following code to reproduce: 
```
    static void Main(string[] args)
    {

        QuestPDF.Settings.License = LicenseType.Community;
        var doc = Document.Create(container => {
            container.Page(page => {
                page.Size(PageSizes.A4);
                page.Margin(1, Unit.Centimetre);

                page.Header().PaddingBottom(10).Background(Colors.Teal.Lighten4).PaddingHorizontal(5).Row(row => {
                    row.RelativeItem().AlignLeft().Text("Some text in Heder left");
                    row.RelativeItem().AlignRight().Text("SomeText to the rigth");
                });

                page.Footer().AlignCenter().Text(x => {
                    x.Span("Page ");
                    x.CurrentPageNumber();
                });

                page.Content().Column(x => {
                    x.Spacing(10);

                    // Use this image to slide the following text item down towards the Page Break ...
                    // Y = 118 works. Y = 119,120 does not work! Y=121 works again with text rendered to the next page.
                    x.Item().Image(Placeholders.Image(100, 119));

                    x.Item().Padding(5).Text(Placeholders.LoremIpsum());

                    x.Item().Table(t => {
                        t.ColumnsDefinition(columns => {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });
                        for (int i = 1; i < 5; i++) {
                            t.Cell().Image(Placeholders.Image(100, 70));
                        }
                    });
                });
            });
        });
        doc.GeneratePdf("c:\\qtemp\\Test.pdf");
        doc.ShowInCompanion();
    }
}
```

**Expected behavior**
Drawing should be ok without workaround.

**Environment**
TargetFramework net9.0
PackageReference Include="QuestPDF" Version="2024.12.1"
Windows 11 Pro 24H2

** Additional Context **
Adding a 1Pixel Padding to the top of the table also fixes (avoids) the Exception!
`x.Item().PaddingTop(1).Table(t => { `

**Comment by jaguarxii** [comment]
Same issue, in my case some "spacing" statements where causing this issue, it is random and can happen in different scenarios

**Comment by MarcinZiabek** [comment]
Thank you for being so patient 😄 

@RobertK66 Could you please try the `2024.12.2` release that may fix the problem?

@jaguarxii If the `2024.12.2` does not fix your issue, could you please prepare a minimal example and share it in a new issue?

**Comment by RobertK66** [comment]
Yes, I can confirm 2024.12.2 fixes this problem. Thx. for the fix. The workaround with a padding of 1 around all my image tables also proved to be stable. I really love the easiness of usage this library ;-).
