### ISSUE TITLE
Example project fails

### ISSUE THREAD

**Issue by davidkdb** [QuestPDF/QuestPDF#112]
Hi,

Running on Visual Studio 2019, Windows 11, all latest updates.

When running the example project it fails at document.GeneratePdf(filePath);

QuestPDF.Drawing.Exceptions.DocumentDrawingException
  HResult=0x80131500
  Message=An exception occured during document drawing.
  Source=QuestPDF
  StackTrace:
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, Container content, DocumentMetadata documentMetadata, DebuggingState debuggingState)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at QuestPDF.ExampleInvoice.Program.Main(String[] args) in C:\Users\ddebono\Source\repos\QuestPDF-ExampleInvoice-main\QuestPDF-ExampleInvoice-main\Program.cs:line 21

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentNullException: Value cannot be null. (Parameter 'key')

**Comment by MarcinZiabek** [comment]
Hello 😁 Thank you for finding this issue! I might have accidentally pushed a code update that covers changes of the beta release. At that moment, QuestPDF had an insignificant bug causing the mentioned exception. I have just published a fixed version. I am very sorry for this inconvenience.
