### ISSUE TITLE
Help! I can't get this working on Windows Server 2019 DC (AWS)

### ISSUE THREAD

**Issue by jheliker** [QuestPDF/QuestPDF#137]
Hello - 

First off, thanks for an amazing PDF library. I've really been enjoying learning it. 

I'm struggling to get an application deployed correctly, and I'm hoping it's my own lack of understanding at fault.

On my own PC, Windows 10 Pro, I can build AnyCPU, x86, and x64 and they run perfectly. But on Windows Server 2019 DC running in AWS (fresh VM, with Visual C++ Redistributable for Visual Studio 2015 with Update 3 for Skia), I get this error no matter what the platform:

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at QuestPDF.Drawing.SkiaDocumentCanvasBase.EndDocument()
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, Container content, DocumentMetadata documentMetadata, DebuggingState debuggingState)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at AdIT_SCTE10435_ParserService.CloudServiceAPI.GetTSAnalysisReport(String ID) in (my project)
   at SyncInvokeGetTSAnalysisReport(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)
   at System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)
   at System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)
   at System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.Runtime.InputQueue`1.AsyncQueueReader.Set(Item item)
   at System.Runtime.InputQueue`1.EnqueueAndDispatch(Item item, Boolean canDispatchOnThisThread)
   at System.Runtime.InputQueue`1.EnqueueAndDispatch(T item, Action dequeuedCallback, Boolean canDispatchOnThisThread)
   at System.ServiceModel.Channels.SingletonChannelAcceptor`3.Enqueue(QueueItemType item, Action dequeuedCallback, Boolean canDispatchOnThisThread)
   at System.ServiceModel.Channels.HttpPipeline.EnqueueMessageAsyncResult.CompleteParseAndEnqueue(IAsyncResult result)
   at System.ServiceModel.Channels.HttpPipeline.EnqueueMessageAsyncResult.HandleParseIncomingMessage(IAsyncResult result)
   at System.Runtime.AsyncResult.SyncContinue(IAsyncResult result)
   at System.ServiceModel.Channels.HttpPipeline.EmptyHttpPipeline.BeginProcessInboundRequest(ReplyChannelAcceptor replyChannelAcceptor, Action dequeuedCallback, AsyncCallback callback, Object state)
   at System.ServiceModel.Channels.HttpChannelListener`1.HttpContextReceivedAsyncResult`1.ProcessHttpContextAsync()
   at System.ServiceModel.Channels.HttpChannelListener`1.BeginHttpContextReceived(HttpRequestContext context, Action acceptorCallback, AsyncCallback callback, Object state)
   at System.ServiceModel.Channels.SharedHttpTransportManager.EnqueueContext(IAsyncResult listenerContextResult)
   at System.ServiceModel.Channels.SharedHttpTransportManager.OnGetContextCore(IAsyncResult listenerContextResult)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.ListenerAsyncResult.IOCompleted(ListenerAsyncResult asyncResult, UInt32 errorCode, UInt32 numBytes)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by MarcinZiabek** [comment]
Hello 😁 What version exactly are you using?

**Comment by jheliker** [comment]
Hello -

Thank you for getting back to me!

I'm using QuestPDF 2022.2.6 from NuGet.

**Comment by MarcinZiabek** [comment]
Can you please show the code that generates the PDF? The code that takes the document object and calls the `GeneratePDF` method?

**Comment by jheliker** [comment]
It's used in a WCF API to return a Stream:

      `public Stream GetTSAnalysisReport(string ID)
        {
            TSAnalysisRecord tsar = GetTSAnalysisRecord(ID);
            if (tsar != null)
            {
                var document = new SCTE35TSAnalysisReport(tsar);
                MemoryStream ms = new MemoryStream();
                document.GeneratePdf(ms);
                ms.Position = 0;
                return ms;
            }

            return null;
        }`

**Comment by jheliker** [comment]
@MarcinZiabek just so you know... I tried writing the PDF to a temporary file first and then returning a FileStream - still crashes hard inside the document.GeneratePdf() call, but only on Windows Server 2019 DC VM in AWS - still works great on my own Windows 10 Pro PC.

**Comment by jheliker** [comment]
@MarcinZiabek one more data point... I spun up the same application on the oldest version of Windows Server I could find in AWS, which is 2012 R2. Exact same issue is happening there.

**Comment by MarcinZiabek** [comment]
1. Can you please try to simplify the PDF document content? E.g. test a simple page with just a short text.
2. Does your document consists of data-heavy content, e.g. many images?
3. Do you use any custom DPI metadata?
4. Can you please try to set the DocumentMetadata.DocumentLayoutExceptionThreshold to 5? There is a special metadata method in the IDocument interface.

**Comment by MarcinZiabek** [comment]
I have also created a [minimal example that renders a PDF document](https://github.com/MarcinZiabek/skiasharp-pdf-minimal) using QuestPDF data flow. Can you please run the code on your server?

**Comment by jheliker** [comment]
Hi @MarcinZiabek 

Thanks for your help with this.

I tried removing all the images and using only simple text - no change.

There were up to 5 images in the test code I have been using.

No custom DPI metadata.

I set the DocumentLayoutExceptionThreshold to 5 with the below code - also no change - still crashing hard with AccessViolationException.

`        public DocumentMetadata dm { get; set; }

        public TSAnalysisRecord Model { get; }

        public SCTE35TSAnalysisReport(TSAnalysisRecord model)
        {
            Model = model;

            dm = new DocumentMetadata();
            dm.DocumentLayoutExceptionThreshold = 5;
        }

        public DocumentMetadata GetMetadata() => dm;
`

**Comment by jheliker** [comment]
@MarcinZiabek regarding your minimal example... I am not set up for .NET 6, still running Visual Studio 2019, so I'm struggling to open your project. Any chance you can just provide an x86 binary?

Thank you!

**Comment by MarcinZiabek** [comment]
Hello, please try once again 😁 

https://github.com/MarcinZiabek/skiasharp-pdf-minimal

**Comment by MarcinZiabek** [comment]
Thank you. Can you please redo the testing to check if the web environment is causing this issue? You can just add a simple endpoint to your application. To be honest, I am still not sure where exactly the is issue... We are making progress though.

**Comment by jheliker** [comment]
Fascinating... I added an endpoint with the following code. It works on the Windows 10 Pro machine, it does not on Windows Server 2012 R2 nor Windows Server 2019 DC. There appears to be a conflict for the reference to System.Buffers. 

The test endpoint is exposed publicly, you can hit if if you like:
https://scte10435parser.middleman.tv/skia-sharp-test

```
        public Stream RunSkiaSharpTest()
        {
            // input stream
            MemoryStream stream = new MemoryStream();

            // initialize
            var document = SKDocument.CreatePdf(stream);

            // begin page
            var canvas = document.BeginPage(400, 300);

            // draw
            using (SKPaint paint = new SKPaint())
            {
                paint.Color = SKColors.DarkGreen;
                paint.TextAlign = SKTextAlign.Center;

                canvas.DrawRect(50, 50, 300, 150, paint);
                canvas.DrawText("This is test", 200, 250, paint);

                // end page
                document.EndPage();
                canvas.Dispose();

                // end document
                canvas.Dispose();
                document.Close();
                document.Dispose();

                stream.Position = 0;
                return stream;
            }
        }
```

The server encountered an error processing the request. Please see the [service help page](http://scte10435parser.middleman.tv/help) for constructing valid requests to the service. The exception message is 'Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'. See server logs for more details. The exception stack trace is:

at SkiaSharp.Utils.RentedArray`1..ctor(Int32 length) at SkiaSharp.SKManagedWStream.OnWrite(IntPtr buffer, IntPtr size) at SkiaSharp.SKAbstractManagedWStream.WriteInternal(IntPtr s, Void* context, Void* buffer, IntPtr size) at SkiaSharp.SkiaApi.sk_document_begin_page(IntPtr document, Single width, Single height, SKRect* content) at SkiaSharp.SKDocument.BeginPage(Single width, Single height) at AdIT_SCTE10435_ParserService.CloudServiceAPI.RunSkiaSharpTest() in C:\Users\James Heliker\source\repos\middlemansoftware\adit-scte10435-parser-service\src\AdIT_SCTE10435_ParserService\CloudServiceAPI.cs:line 416 at SyncInvokeRunSkiaSharpTest(Object , Object[] , Object[] ) at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs) at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc) at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

<img width="402" alt="System BuffersDLLInfo" src="https://user-images.githubusercontent.com/6565523/157714287-9815f4e9-0ad7-42a1-b0ed-666af90c2886.png">

**Comment by MarcinZiabek** [comment]
Interesting! But it does not help us much 😁 From now on, I expect that this issue is not within the QuestPDF code. However, it would be nice to identify the root cause. Do you know at which point the exception is thrown? Maybe there are some incorrect namespace mappings in your webconfig file? I am using SkiaSharp on my Azure environments and never identified any issue.

**Comment by girlpunk** [comment]
Won't be as easy as troubleshooting managed (i.e. c#) code, but you can generate a dump file when the test application crashes , which should reveal whereabout within QuestPDF the access violation is coming from. Follow these instructions to set a few registry keys, then recreate the crash. You should get a .dmp file that can be opened in Visual Studio as if a breakpoint was hit just as the violation happened.

https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm

**Comment by jheliker** [comment]
@MarcinZiabek I found the resolution here, it is working now. Thank you for your help!

https://github.com/dotnet/runtime/issues/27117
