### ISSUE TITLE
NullReferenceException on .Text() with null

### ISSUE THREAD

**Issue by zhang-li-80** [QuestPDF/QuestPDF#141]
Calling `.Text(null)` will cause a `NullReferenceException`.

It should treat it as an empty string, or not render anything out.

**ConsoleApp1.csproj**:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2022.3.0" />
  </ItemGroup>
</Project>
```

**Program.cs**:
```csharp
// See https://aka.ms/new-console-template for more information
using QuestPDF.Fluent;

Document.Create(container =>
{
    var item = new Item();
    container.Page(page =>
    {
        page.Content()
            .Column(x =>
            {
                x.Item().Text(item.Name);  // Name is null here
            });
    });
})
.GeneratePdf("hello.pdf");

internal class Item
{
    internal string? Name { get; set; }
}
```

**Stack trace**:
```
   at QuestPDF.Fluent.TextDescriptor.Span(String text)
   at QuestPDF.Fluent.TextExtensions.<>c__DisplayClass2_0.<Text>b__0(TextDescriptor x)
   at QuestPDF.Fluent.TextExtensions.Text(IContainer element, Action`1 content)
   at QuestPDF.Fluent.TextExtensions.Text(IContainer element, Object text)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__2(ColumnDescriptor x) in D:\Development\ConsoleApp1\ConsoleApp1\Program.cs:line 12
```

Looks similar to #48, but that has been closed.

**Comment by MarcinZiabek** [comment]
Hello! I am very sorry for this issue. I might have introduced this bug while I was working on the API refactoring 😥 I have created unit test that should prevent me from making this type of mistake again. 

I have just released the [QuestPDF 2022.3.1](https://www.nuget.org/packages/QuestPDF/2022.3.1) that should have that bug fixed. Please try it and confirm 😁

**Comment by zhang-li-80** [comment]
Can confirm it works now.

**Comment by MarcinZiabek** [comment]
Perfect! Thank you for finding this issue. Have fun with QuestPDF 😀
