### ISSUE TITLE
Wrong version of libSkiaSharp for previewer on linux

### ISSUE THREAD

**Issue by VladimirV99** [QuestPDF/QuestPDF#212]
**Describe the bug**
The linux version of the previewer tool comes with libSkiaSharp version 2.80.2 which is incompatible, so it crashes on startup with the following stack trace:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.2) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [80.3, 81.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.GRGlInterface..ctor(IntPtr h, Boolean owns)
   at SkiaSharp.GRGlInterface.GetObject(IntPtr handle)
   at SkiaSharp.GRGlInterface.CreateOpenGl(GRGlGetProcedureAddressDelegate get)
   at Avalonia.Skia.GlSkiaGpu..ctor(IPlatformOpenGlInterface openGl, Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaGpu.cs:line 24
   at Avalonia.Skia.PlatformRenderInterface..ctor(ISkiaGpu skiaGpu, Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 37
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs:line 20
   at Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 304
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 174
   at Program.<Main>$(String[] args) in D:\QuestPDF\QuestPDF.Previewer\Program.cs:line 22
```
Manually downloading version 2.80.3 of libSkiaSharp and replacing the installed version fixes the issue

**To Reproduce**
Install questpdf-previewer on a linux machine and try to run it

**Comment by MarcinZiabek** [comment]
Would you like to elaborate more on what change have performed to fix this issue? 😁

**Comment by VladimirV99** [comment]
I replaced the `libSkiaSharp.so` files that are shipped with the QuestPDF Previewer nupkg file (located at `tools/net6.0/any/runtimes/linux-[arch]/native/libSkiaSharp.so`) with ones downloaded from [SkiaSharp.NativeAssets.Linux.NoDependencies](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies) version 2.80.3. No code changes are needed, this is just a nuget package issue

**Comment by jeroenvervaeke** [comment]
I can confirm this issue.

Installing the previewer and running it using the following command results in the same error:
```bash
dotnet tool install QuestPDF.Previewer --global
questpdf-previewer
```

I can also confirm that the workaround provided by @VladimirV99 works.

1. Download [SkiaSharp.NativeAssets.Linux.NoDependencies 2.80.3](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies/2.80.3)
2. Unzip the file
3. Download [QuestPDF.Previewer](https://www.nuget.org/packages/QuestPDF.Previewer/)
4. Unzip the file
5. Copy the files in `[skiasharp folder]/runtimes` _over_ (replace) `[questpdf.previewer folder]/tools/net6.0/any/runtimes/`
6. Zip the new modified folder and change the extension from `zip` to `nupgk`
7. Create a temp folder and place the package you just created in it
8. In that folder run `dotnet tool install --global --add-source . QuestPDF.Previewer --global`
9. Run `questpdf-previewer`, everything should work fine now.

**Comment by MarcinZiabek** [comment]
OK, so it looks like we need to build separate targets depending on the operating system. Conditionally, just for Linux, we need to add one more nuget dependency (SkiaSharp.NativeAssets.Linux.NoDependencies 2.80.3 mentioned by @jeroenvervaeke). I will try to create a test release of QuestPDF.Previewer with such dependency in a couple of days 😊

**Comment by MarcinZiabek** [comment]
In the 2022.6 release, I have added additional nuget dependencies that should allow to run the QuestPDF Previewer on Linux and MacOS. If anybody is willing to try, please let me know 😁 I hope that the new version will work as expected.

**Comment by VladimirV99** [comment]
Unfortunately, it still doesn't work. According to the last modified time of the linux native assets they are still from September 11 2020. However, replacing the dependency `SkiaSharp.NativeAssets.Linux.NoDependencies` with `SkiaSharp.NativeAssets.Linux` seems to work, though I still have to test it on another machine to make sure.

**Comment by VladimirV99** [comment]
I tested it further and changing
```xml
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.4" />
```
to
```xml
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.4" />
```
in `QuestPDF.Previewer.csproj` adds the appropriate version of SkiaSharp for linux.

**Comment by MarcinZiabek** [comment]
The problem mentioned in this issue has already been addressed. Furthermore, the QuestPDF Previewer tool has been replaced by the QuestPDF Companion App, which brings enhanced features. To learn more, please visit: [QuestPDF Companion App](https://www.questpdf.com/companion/usage.html).

Since there has been no recent activity, I’m closing this issue. If you have a similar request in the future, please feel free to open a new GitHub issue. Thanks for your feedback! ❤️
