### ISSUE TITLE
System.TypeInitializationException on macOS

### ISSUE THREAD

**Issue by Kopkako** [QuestPDF/QuestPDF#227]
**Describe the bug**
When using SkiaSharp as a dependency of QuestPDF and trying their sample, I get the following error:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSkiaSharp, 0x0001): tried: 'liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file), '/Users/Kopkako/RiderProjects/ConsoleApp1/ConsoleApp1/bin/Debug/net6.0/liblibSkiaSharp' (no such file)
   at SkiaSharp.SkiaApi.sk_managedwstream_set_procs(SKManagedWStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedWStream..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKAbstractManagedWStream..ctor(Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream, Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream)
   at SkiaSharp.SKDocument.CreatePdf(Stream stream, SKDocumentPdfMetadata metadata)
   at QuestPDF.Drawing.PdfCanvas..ctor(Stream stream, DocumentMetadata documentMetadata)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at Program.<Main>$(String[] args) in /Users/Kopkako/RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 9

Process finished with exit code 134.

```

This only happens on macOS, apparently - a friend confirmed that it only happened for him on macOS, not Windows.
I am on the latest version of macOS (12.4) with a 2021 MacBook Pro M1.

**To Reproduce**
Create a new dotnet 6 console application.
Import QuestPDF latest version (2022.5.0) via NuGet.
Use the following sample code (from the QuestPDF docs):

```cs
Document.Create(container =>
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(2, Unit.Centimetre);
            page.PageColor(Colors.White);
            page.DefaultTextStyle(x => x.FontSize(20));

            page.Header()
                .Text("Hello PDF!")
                .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);

            page.Content()
                .PaddingVertical(1, Unit.Centimetre)
                .Column(x =>
                {
                    x.Spacing(20);

                    x.Item().Text(Placeholders.LoremIpsum());
                    x.Item().Image(Placeholders.Image(200, 100));
                });

            page.Footer()
                .AlignCenter()
                .Text(x =>
                {
                    x.Span("Page ");
                    x.CurrentPageNumber();
                });
        });
    })
    .GeneratePdf("hello.pdf");
```

**Expected behavior**
A PDF should be produced.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Bebo-Maker** [comment]
This exception comes from SkiaSharp.
For some targets you need to install additional nuget packages.
I believe for macOS you need [this](https://www.nuget.org/packages/SkiaSharp.NativeAssets.macOS/).

Also see #177

**Comment by Kopkako** [comment]
> This exception is thrown by SkiaSharp. For some targets you need to install additional nuget packages. I believe for macOS you need [this](https://www.nuget.org/packages/SkiaSharp.NativeAssets.macOS/) package.
> 
> Also see #171

Thanks for your reply!

I installed the additional macOS native package, but it still did not work.
Then, out of frustration, I installed the Linux native package `SkiaSharp.NativeAssets.Linux` and now it finally works!

**Comment by xiwuou** [comment]
狗屎！我还以为只有我会遇到这种情况，我甚至怀疑是我的 Mac m1 坏了！

**Comment by wieslawsoltes** [comment]
This requires latest SkiaSharp and using .NET 6 MSBuild tools.

https://www.nuget.org/packages/SkiaSharp/2.88.1-preview.1 or later

**Comment by AverageCakeSlice** [comment]
Has anyone else run into this issue? I'm trying to run an Azure Functions instance locally using the Azure Functions Core Tools on my mac. I have an Intel MBP, so no arm weirdness there, but I get the libSkiaSharp exception no matter what dependencies I install. I've tried NativeAssets.Linux, NativeAssets.Linux.NoDependencies, NativeAssets.macOS, even installing all of the HarfBuzzSharp packages as well, but to no avail. 

I'm using Azure Functions V4 with .NET 6 LTS.

**Comment by bhtz** [comment]
Same 2021 MacBook Pro M1 here & i managed to generate a file with this configuration (asp net with .NET 6 LTS not Azure Functions V4) : 

QuestPDF + HarfBuzzSharp.NativeAssets.Linux + SkiaSharp.NativeAssets.Linux

<PackageReference Include="QuestPDF" Version="2022.6.3" />
<PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="2.8.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.1-preview.1" />

**Comment by MarcinZiabek** [comment]
Since the 2024.3.0 release, QuestPDF no longer depends on SkiaSharp and HarfBuzzSharp. As a result, this issue has been resolved.

I’m closing this issue due to inactivity. If you encounter a similar issue or have a related request, please feel free to open a new GitHub issue. Thank you for your feedback! ❤️
