### ISSUE TITLE
[Bug] 2022.6.1 on Linux - System.DllNotFoundException: Unable to load shared library 'libHarfBuzzSharp' or one of its dependencies

### ISSUE THREAD

**Issue by mtosic** [QuestPDF/QuestPDF#246]
When upgrading to 2022.6.1 document generation breaks on Linux (Azure app service on Linux).
When started locally (on Windows) everything works fine.

If I revert to old version (2022.5.0) everything works fine.
I've tried expliclity adding SkiaSharp.HarfBuzz, but that didn't help.

Anyone knows what might be an issue?

**Comment by MarcinZiabek** [comment]
Hi 😁 Please try to install this package: https://www.nuget.org/packages/HarfBuzzSharp.NativeAssets.Linux/2.8.2 (or something similar from this naming convention).

If it does help, I can override the exception message from the HurfBuzzSharp library to make it more obvious what to do.

**Comment by mtosic** [comment]
It works like a charm now, thank you so much!

**Comment by MarcinZiabek** [comment]
The 2022.6.2 release throws more detailed exception in this case, hopefully helping others to resolve the problem faster😁

**Comment by tango-charly** [comment]
I have the same issue with Blazor WASM (Windows).
I tried to install all HardBuzzSharp package 😂
.Webassembly
.Windows32
even Linux !

But nothing works, why dependencies are not included with your package ?

**Comment by genifycom** [comment]
Cannot get this to work in Blazor Webassembly. Does anyone have a working example?

csproj includes the following:

	<ItemGroup>
		<PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="2.8.2" />
		<PackageReference Include="QuestPDF" Version="2022.6.3" />
		<PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.88.0" />
		<PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.0" />
	</ItemGroup>

The error is:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: libHarfBuzzSharp
System.DllNotFoundException: libHarfBuzzSharp
   at HarfBuzzSharp.Blob.Create(IntPtr data, Int32 length, MemoryMode mode, ReleaseDelegate releaseProc)
   at HarfBuzzSharp.Blob..ctor(IntPtr data, Int32 length, MemoryMode mode, ReleaseDelegate releaseDelegate)
   at SkiaSharp.HarfBuzz.BlobExtensions.ToHarfBuzzBlob(SKStreamAsset asset)
   at QuestPDF.Drawing.FontManager.<>c__DisplayClass13_0.<ToShaperFont>b__0(Object _)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[HarfBuzzSharp.Font, HarfBuzzSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756]].GetOrAdd(Object key, Func`2 valueFactory)
   at QuestPDF.Drawing.FontManager.ToShaperFont(TextStyle style)
   at QuestPDF.Drawing.TextShaper..ctor(TextStyle style)

**Comment by MarcinZiabek** [comment]
@tango-charly QuestPDF relies on packages coming from the SkiaSharp library (both SkiaSharp nad  HarfBuzzSharp). Both packages are managed by Microsoft. Futhermore, there are dependend on additional unmanaged libraries (C++ code, e.g. Skia from Google). Those libraries are compiled seperatelly for each operating system / runtime environment.

I don't want to include those dependencies (as implicit nuget packages), as it will singificantly increase deployment package of all projects that use QuestPDF. You will need to download nugets and deploy associated dlls not only for your proper runtime but also all unused ones. E.g. application runs on Windows machine, but compilation result contains dlls for Linux, macOS, Android, WebAssembly, etc. 

I doesn't make sense.

**Comment by FakeRayBanz** [comment]
Hi, I am also having an issue with System.DllNotFoundException: libHarfBuzzSharp using Blazor WebAssembly. Downgrading to 2022.5.0 works. I tried installing HarfBuzzSharp separately but it didn't work. Do you know which packages are necessary or any update on bundling a higher version of SkiaSharp? :)

**Comment by tossnet** [comment]
Hi, I have the same problem on Blazor WebAssembly. Everything works fine until version 2022.2.7. But from the version 2022.3.0, I have the same error :
`blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: libHarfBuzzSharp
System.DllNotFoundException: libHarfBuzzSharp
   at HarfBuzzSharp.Buffer..ctor()
   at QuestPDF.Drawing.TextShaper.Shape(String text)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.MeasureWithoutCache(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.Measure(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.TextBlock.<DivideTextItemsIntoLines>g__GetNextLine|25_0(<>c__DisplayClass25_0& )
   at QuestPDF.Elements.Text.TextBlock.DivideTextItemsIntoLines(Single availableWidth, Single availableHeight)+MoveNext()
   at System.Collections.Generic.List`1[[QuestPDF.Elements.Text.Calculation.TextLine, QuestPDF, Version=2022.9.1.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TextLine](IEnumerable`1 source)
   at QuestPDF.Elements.Text.TextBlock.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
`

I tried to use the following packages to no avail:
<PackageReference Include="SkiaSharp.HarfBuzz" Version="2.88.3" />
or
<PackageReference Include="HarfBuzzSharp" Version="2.8.2.3" />
<PackageReference Include="SkiaSharp.HarfBuzz" Version="2.88.3" />

If anyone have an idea...

**Comment by Roytin** [comment]
<PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="2.8.2.3" />

**Comment by MarcinZiabek** [comment]
Since the 2024.3.0 release, QuestPDF no longer depends on SkiaSharp and HarfBuzzSharp, resolving this type of issue. Unfortunately, support for WASM has been discontinued.

I’m closing this issue due to inactivity. If you encounter a similar issue or have a related request, please feel free to open a new GitHub issue. Thank you for your feedback! ❤️
