### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. .NetCore 5.0 C#

### ISSUE THREAD

**Issue by kir0riwal** [QuestPDF/QuestPDF#266]
Hello Marcin,

I used QuestPDF nuget package in project .Net Core 5.0 using C#, and pushed my code in Docker Linux box. There it started throwing error like below -

I did triaging based on google articles and QuestPDF documentations-
1.  Added following packages -
   a) QuestPDF (2022.6.1)
   b) SkiaSharp.NativeAssets.Linux(2.88.0)
   c) SkiaSharp.NativeAssets.Linux.NoDependencies(2.88.0)
   d) HarfBuzzSharp.NativeAssets.Linux(2.8.2)
   e) Jellyfin.skiaSharp.NativeAssets.LinuxArm(1.68.1)

2. Added this command in Docker file - **RUN apt-get update && apt-get install -y libfontconfig1**
****
But after pushing this code in Docker, it throwing error -

Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.
---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory

at SkiaSharp.SkiaApi.sk_managedwstream_set_procs(SKManagedWStreamDelegates procs)

at SkiaSharp.SKAbstractManagedWStream..cctor()

Also in your last release notes, you mentioned about this error, so it seems like you aware about this error and its fix

Integrated the text-shaping algorithm. This change significantly improves the Unicode compatibility. Also, it extends support for more advanced languages (e.g. Arabic) that:

1) Combine multiple text characters and display them as a single visual glyph.
2) Are displayed in the right-to-left order.

Improved the exception message when SkiaSharp throws the TypeInitializationException. On some operating systems, SkiaSharp requires additional dependencies installed as nuget packages.

This change should help developers determine how to choose and install them correctly.

Fixed: a rare case when the Row.AutoItem() does not correctly calculate the width of its content.
Fixed: the QuestPDF Previewer does not work with content-rich documents.

Please share your expert advice in order to resolve this error, Any help on this is appreciated.

**Comment by MarcinZiabek** [comment]
> Also in your last release notes, you mentioned about this error, so it seems like you aware about this error and its fix

Yes, this is a typical SkiaSharp + HarfBuzz problem about loading additional dependencies, depending on the deployment environment. What I am attempting to do is to wrap this excpetion with additional message that is hopefully more informative and helpful for developers. 

My guess here would be to also check nuget versions. QuestPDF automatically improtats SkiaSharp with version `2.80.4` and I would be looking for dependency nugets with similar versions. Please make a try 😁

**Comment by jonnyze** [comment]
I had simliar issues. I had to remove  SkiaSharp.NativeAssets.Linux(2.88.0) and use only  SkiaSharp.NativeAssets.Linux.NoDependencies(2.88.0) to resolve the issue.

**Comment by mykhailopylyp** [comment]
In my case, I didn't have SkiaSharp.NativeAssets.Linux and HarfBuzzSharp.NativeAssets.Linux installed with NuGet.
![image](https://user-images.githubusercontent.com/17161067/221182496-3ac688b8-ba12-479f-be3b-3da5bd01c5e2.png)

Installing the following packages resolved the issue.
`SkiaSharp.NativeAssets.Linux.NoDependencies`
`HarfBuzzSharp.NativeAssets.Linux`

**Comment by MarcinZiabek** [comment]
Starting with the 2024.3.0 release, QuestPDF has removed its dependencies on SkiaSharp and HarfBuzzSharp, effectively resolving this issue. However, this update also means that WASM support has been discontinued.

Since there has been no recent activity, I’m closing this issue. If you experience a similar problem or have a related request, feel free to open a new GitHub issue. I appreciate your feedback! ❤️
