### ISSUE TITLE
The typeface 'Calibri' could not be found. [https://github.com/QuestPDF/QuestPDF/issues/132#issuecomment-1165274851]

### ISSUE THREAD

**Issue by kir0riwal** [QuestPDF/QuestPDF#267]
Hello Marcin -

Here is link to my conversation - 
[The typeface 'Calibri' could not be found. [https://github.com/QuestPDF/QuestPDF/issues/132#issuecomment-1165274851](https://github.com/QuestPDF/QuestPDF/issues/132#issuecomment-1165274851)) 

this ""LibreBarcode39-Regular.ttf"" , do I need to put in Bin folder in local computer before starting Docker Build ?
or my question is where to place this file in application structure, so that using below command font manager could get it ?

// perform similar invocation only once, when the application starts or during its initialization step
FontManager.RegisterFont(File.OpenRead("LibreBarcode39-Regular.ttf")); // use file name

If I write code
First I copied calibri.ttf in bin /.net5.0/release folder and then write below code
FontManager.RegisterFont(File.OpenRead("calibri.ttf"));

But after deployment to docker, it throwing error -
System.IO.FileNotFoundExceptio : Couls not find file '/app/calibri.ttf'.

In further Triaging.... I installed two fonts in Docker Linux box, which I could see installed in power shell linux..

Docker file change :
RUN apt-get install -y fontconfig libfontconfig fonts-crosextra-carlito fonts-crosextra-caladea && fc-cache -f -v

But QuestPDF still not picking up these default fonts rather it keep erroring out for The typeface 'Calibri' could not be found.

Appreciate your help....

**Comment by Sergey-Terekhin** [comment]
We have similar issue:
we use custom font for reports and register it via `FontManager`. Calibri font is not used anywhere. But when we try to create report in linux environment, we get error:
```
The typeface 'Calibri' could not be found. Please consider the following options: 1) install the font on your operating system or execution environment. 2) load a font file specifically for QuestPDF usage via the QuestPDF.Drawing.FontManager.RegisterFontType(Stream fileContentStream) static method
```

Any workarounds except to have a copy of Calibri font (it's license violation)?

**Comment by Sergey-Terekhin** [comment]
Yes, I set `DefaultTextStyle` on every document page and it works. But `TextStyle.LibraryDefault` is defined as `internal static` and is used somewhere in library itself and fails on linux

**Comment by Bebo-Maker** [comment]
`TextStyle.LibraryDefault.FontFamily` is `Calibri`. Looks like this line is the problem:
https://github.com/QuestPDF/QuestPDF/blob/2a0b133185cc07473db5ad52f622a96f6b754c80/QuestPDF/Drawing/DocumentGenerator.cs#L67

**Comment by Sergey-Terekhin** [comment]
> `TextStyle.LibraryDefault.FontFamily` is `Calibri`. Looks like this line is the problem:
> 
> https://github.com/QuestPDF/QuestPDF/blob/2a0b133185cc07473db5ad52f622a96f6b754c80/QuestPDF/Drawing/DocumentGenerator.cs#L67

Yes, seems you're right

**Comment by genifycom** [comment]
I am getting this in Windows 11 as well. Why would this be when Calibri is available by default in Windows?

This is a Webassembly Blazor App running in Windows 11.
I am not explicitly using fonts or fonts sizes anywhere. It is essentially just the basic Invoice app. It works from Unit test but not from the Blazor code.

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The typeface 'Calibri' could not be found. Please consider the following options: 1) install the font on your operating system or execution environment. 2) load a font file specifically for QuestPDF usage via the QuestPDF.Drawing.FontManager.RegisterFontType(Stream fileContentStream) static method.
System.ArgumentException: The typeface 'Calibri' could not be found. Please consider the following options: 1) install the font on your operating system or execution environment. 2) load a font file specifically for QuestPDF usage via the QuestPDF.Drawing.FontManager.RegisterFontType(Stream fileContentStream) static method.
   at QuestPDF.Drawing.FontManager.<ToPaint>g__GetTypeface|11_2(TextStyle style)
   at QuestPDF.Drawing.FontManager.<ToPaint>g__Convert|11_1(TextStyle style)
   at QuestPDF.Drawing.FontManager.<>c__DisplayClass11_0.<ToPaint>b__0(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SkiaSharp.SKPaint, SkiaSharp, Version=2.88.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756]].GetOrAdd(Object key, Func`2 valueFactory)
   at QuestPDF.Drawing.FontManager.ToPaint(TextStyle style)
   at QuestPDF.Drawing.FontManager.<>c__DisplayClass13_0.<ToShaperFont>b__0(Object _)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[HarfBuzzSharp.Font, HarfBuzzSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756]].GetOrAdd(Object key, Func`2 valueFactory)
   at QuestPDF.Drawing.FontManager.ToShaperFont(TextStyle style)
   at QuestPDF.Drawing.TextShaper..ctor(TextStyle style)
   at QuestPDF.Drawing.FontManager.<>c__DisplayClass14_0.<ToTextShaper>b__0(Object _)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[QuestPDF.Drawing.TextShaper, QuestPDF, Version=2022.6.2.0, Culture=neutral, PublicKeyToken=null]].GetOrAdd(Object key, Func`2 valueFactory)
   at QuestPDF.Drawing.FontManager.ToTextShaper(TextStyle style)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.MeasureWithoutCache(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.Measure(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.TextBlock.<DivideTextItemsIntoLines>g__GetNextLine|21_0(<>c__DisplayClass21_0& )
   at QuestPDF.Elements.Text.TextBlock.DivideTextItemsIntoLines(Single availableWidth, Single availableHeight)+MoveNext()
   at System.Collections.Generic.List`1[[QuestPDF.Elements.Text.Calculation.TextLine, QuestPDF, Version=2022.6.2.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TextLine](IEnumerable`1 source)
   at QuestPDF.Elements.Text.TextBlock.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Row.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Row.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Elements.Decoration.<PlanLayout>g__GetDecorationMeasurement|16_0(Element element, <>c__DisplayClass16_0& )
   at QuestPDF.Elements.Decoration.PlanLayout(Size availableSpace)+MoveNext()
   at System.Collections.Generic.List`1[[QuestPDF.Elements.DecorationItemRenderingCommand, QuestPDF, Version=2022.6.2.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[DecorationItemRenderingCommand](IEnumerable`1 source)
   at QuestPDF.Elements.Decoration.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Padding.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Constrained.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Layers.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.DebuggingProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[FreeCanvas](PageContext pageContext, FreeCanvas canvas, Container content, DocumentMetadata documentMetadata, DebuggingState debuggingState)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[PdfCanvas](PdfCanvas canvas, IDocument document)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
   at PFReporting.PFBidCreation.GenerateBidInvoice(PFBid bid, Boolean internalPDF) in C:\Dev\AITC\LambdaBlazor\PFBlazorInventory\PFReporting\PFCustomerBid.cs:line 91
   at PFSupplierTagging.Pages.InventorySummary.EmailInvoiceToBuyerOnly() in C:\Dev\AITC\LambdaBlazor\PFBlazorInventory\PFSupplierTagging\Pages\InventorySummary.razor:line 732
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by Sergey-Terekhin** [comment]
May be default font family should be replaced by `SKTypeface.FromFamilyName("Sans")?.FamilyName` or something like that for any OS and environment

**Comment by Sergey-Terekhin** [comment]
As "dirty" and not completely legal solution (possibly, it violates MS license https://docs.microsoft.com/ru-ru/typography/font-list/calibri) you can copy Calibry font with your project and preload it from stream by `SKFontManager` on startup for example

**Comment by MarcinZiabek** [comment]
QuestPDF currently uses the Lato font as its default and includes it within the NuGet package. Additionally, to improve the development experience, it automatically scans the application deployment folder and registers all available font files.

Since there hasn't been any recent activity, I’m closing this issue. If you have a similar request in the future, don’t hesitate to open a new GitHub issue. Thanks for your feedback! ❤️
