### ISSUE TITLE
AccessViolationException in finalizer thread (v2022.6.3)

### ISSUE THREAD

**Issue by RichardD2** [QuestPDF/QuestPDF#301]
I upgraded a .NET Framework 4.8 / ASP.NET MVC 5 application from v2022.5.0 to v2022.6.3 this morning. This also updated SkiaSharp from 2.80.4-preview.9 to 2.88.0, and added a new reference to HarfBuzzSharp v2.6.1.9.

I tested the code to generate a PDF, which worked as expected.

Some time later, the w3p process crashed with an `AccessViolationException` in the finalizer thread:

> Application: w3wp.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.AccessViolationException
> |-> at SkiaSharp.Internals.PlatformLock+NonAlertableWin32Lock.EnterCriticalSection(IntPtr)
> |-> at SkiaSharp.Internals.PlatformLock+NonAlertableWin32Lock.EnterWriteLock()
> |-> at SkiaSharp.HandleDictionary.DeregisterHandle(IntPtr, SkiaSharp.SKObject)
> |-> at SkiaSharp.SKObject.DeregisterHandle(IntPtr, SkiaSharp.SKObject)
> |-> at SkiaSharp.SKObject.set_Handle(IntPtr)
> |-> at SkiaSharp.SKNativeObject.Dispose(Boolean)
> |-> at SkiaSharp.SKNativeObject.Finalize()

Is this a bug in SkiaSharp, a problem with how QuestPDF uses it, or something wrong in my code?

The only moderately-complicated part of my code is used to create a rounded image:

```csharp
public class RoundedImage : IDynamicComponent<int>
{
    public RoundedImage([NotNull] string imagePath)
    {
        ImagePath = imagePath;
    }

    public string ImagePath { get; }

    int IDynamicComponent<int>.State { get; set; }

    private static SKBitmap LoadImage([NotNull] string imagePath)
    {
        using var stream = File.OpenRead(imagePath);
        return SKBitmap.Decode(stream);
    }

    private static float CalculateImageHeight([NotNull] string imagePath, float width)
    {
        using var image = LoadImage(imagePath);
        return width * image.Height / image.Width;
    }

    public DynamicComponentComposeResult Compose(DynamicContext context)
    {
        string imagePath = ImagePath;
        if (string.IsNullOrEmpty(imagePath) || !File.Exists(imagePath))
        {
            return new();
        }

        var content = context.CreateElement(container =>
        {
            var width = context.AvailableSize.Width;
            var imageHeight = CalculateImageHeight(imagePath, width);

            container.MaxHeight(imageHeight).Canvas((canvas, size) =>
            {
                canvas.Save();
                var canvasRect = SKRect.Create(0, 0, size.Width, size.Height);
                using SKPath path = new();
                path.AddRoundRect(canvasRect, 15f, 15f);
                canvas.ClipPath(path, antialias: true);
                using var image = LoadImage(imagePath);
                var imageRect = SKRect.Create(0, 0, image.Width, image.Height);
                canvas.DrawBitmap(image, imageRect, canvasRect);
                canvas.Restore();
            });
        });

        return new() { Content = content };
    }
}
```

**Comment by RichardD2** [comment]
Looks like it's a bug in SkiaSharp:

https://github.com/mono/SkiaSharp/pull/1817#issuecomment-967799471

**Comment by MarcinZiabek** [comment]
I am testing with the following dependency versions:

```xml
<PackageReference Include="SkiaSharp" Version="2.80.4" />
<PackageReference Include="SkiaSharp.HarfBuzz" Version="2.80.4" />
```

Would you like to downgrade and retest? Maybe it is a regression thing?

In terms of the `AccessViolationException` exception, please go through your code and make sure that all objects implementing the `IDisposable` interface are properly handled. I don't see anything wrong with your implementation at the first glance (except some small performance issues).

Also, please notice, that both dependencies are installed automatically. Technically, there is no need to manually add them to your dependency lists.

**Comment by RichardD2** [comment]
Thanks for the reply. I'll try 2.80.4 to see if that resolves the issue for now.

Unfortunately, MVC applications don't support transitive NuGet dependencies. If you install one package, it installs every package that one depends on, and so on.

Also, I had to explicitly install `2.80.4-preview.9` to get around [the "strong name signature" bug](https://github.com/mono/SkiaSharp/issues/1767) from the `2.80.3` version that QuestPDF `2022.5.0` installed.

**Comment by MarcinZiabek** [comment]
Starting with the 2024.3.0 release, QuestPDF has removed its dependencies on SkiaSharp and HarfBuzzSharp, effectively resolving this problem.

Since there has been no recent activity, I’m closing this issue. If you experience a similar problem or have a related request, feel free to open a new GitHub issue. I appreciate your feedback! ❤️
