### ISSUE TITLE
Previewer does not open on M1 Pro MacOS

### ISSUE THREAD

**Issue by evanrobertson** [QuestPDF/QuestPDF#334]
When `ShowInPreviewer()` is used or attempting to run previewer standalone on M1 Pro previewer fails to open with error:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSkiaSharp, 0x0001): tried: 'liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file), '/Users/evan/Dev/Personal/pdf-test/PdfTest/bin/Debug/net6.0/liblibSkiaSharp' (no such file)
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(ISkiaGpu skiaGpu, Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 27
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs:line 20
   at Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 304
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 174
   at Program.<Main>$(String[] args) in D:\QuestPDF\QuestPDF.Previewer\Program.cs:line 22
```

This is with these 2 packages referenced:
```
<PackageReference Include="QuestPDF" Version="2022.8.2" />
<PackageReference Include="SkiaSharp.NativeAssets.MacOS" Version="2.88"/>
```

Which appears to be an issue with the version of Avalonia being used
https://github.com/AvaloniaUI/Avalonia/discussions/7233

**Comment by jchannon** [comment]
I'm getting this exact error in our CI build, we use docker images to build in CI and our base image is `mcr.microsoft.com/dotnet/sdk:8.0` Any ideas?

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/runtimes/linux/native/libSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/libSkiaSharp.so: cannot open shared object file: No such file or directory
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/libSkiaSharp.so: cannot open shared object file: No such file or directory
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/runtimes/linux/native/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/runtimes/linux/native/libSkiaSharp: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/libSkiaSharp: cannot open shared object file: No such file or directory
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/libSkiaSharp: cannot open shared object file: No such file or directory
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/runtimes/linux/native/liblibSkiaSharp: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.14/liblibSkiaSharp: cannot open shared object file: No such file or directory
/builds/elaway/platform/cpms/helix/src/helix/tests/Helix.Tests/bin/Release/net7.0/liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_version_get_milestone()
   at SkiaSharp.SkiaSharpVersion.get_Native()
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKObject.DeregisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKObject.set_Handle(IntPtr value)
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKObject.Dispose(Boolean disposing)
   at SkiaSharp.SKPaint.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()
```
