### ISSUE TITLE
Error when using GeneratePdf() on ANDROID system in MAUI. System.TypeLoadException & QuestPDF.Drawing.FontManager threw an exception

### ISSUE THREAD

**Issue by YBTopaz8** [QuestPDF/QuestPDF#348]
**Describe the bug:**
In an attempt to generate and write a PDF file on the Internal Storage in **ANDROID 13, API 33** using .NET MAUI, I always, unfailingly, run into a System.TypeLoadException. 
This issue does NOT seem to happen on WINDOWS, despite over 10 tests. 

**To Reproduce:**
In my case, I simply copied this
`Document doc =` [this sample code from official repo, starting from Document.Create(...](https://github.com/QuestPDF/QuestPDF#simplicity-is-the-key)
`string fn = "hello.pdf";`
`string file = Path.Combine(FileSystem.CacheDirectory, fn);`
`doc.GeneratePdf(file);`
All in a function that is called on button click.

**Expected behavior:**
I expect GeneratePdf() to create a pdf file in the location provided.

**Screenshots:**
Here is the exception I got from the SAMPLE code ONLY
![image](https://user-images.githubusercontent.com/41630728/193008414-a37aa68a-6ddb-41a4-a818-90f10233e383.png)

When creating a pdf with containing a Table filled with my list, I get the FIRST error, and upon setting INTO that, I get this second error:
![image](https://user-images.githubusercontent.com/41630728/193010498-2a0e5ec8-f9b7-4cf2-b838-7797c35dcde5.png)

**Additional context**
On My Windows Machine, running win10, everything works like a charm, even right up to the Previewer.
![image](https://user-images.githubusercontent.com/41630728/193017602-cc0176df-55dd-4808-baa0-f3b4f8df2a7d.png)

**Comment by MarcinZiabek** [comment]
What version of SkiaSharp are you using? Best: please provide all nuget dependencies in your solution

**Comment by YBTopaz8** [comment]
> What version of SkiaSharp are you using? Best: please provide all nuget dependencies in your solution

I am not using SkiaSharp anywhere in my project.
The Nuget dependencies are just a few for now, including:

- CommunityToolKit.Mvvm
- Microsoft.Maui.Dependencies
- Microsoft.Maui.Extensions
- QuestPDF
- SQLiteNetExtensions
- sqlite-net-pcl
- SQLitePCLRaw.bundle_green
- SQLitePCLRaw.core
- SQLitePCLRaw.lib.e_sqlite3
- SQLitePCLRaw.provider.dynamic_cdecl
- System.Runtime.InteropServices.NFloat.Internal
- Microsoft.Windows.SDK.BuildTools

The project is very new and I wanted to test the core functionality first, which is, generating a PDF.
If any more information is needed, please let me know.

**Comment by MarcinZiabek** [comment]
I need to know exact versions of those nuget packages.

**Comment by YBTopaz8** [comment]
> I need to know exact versions of those nuget packages.

- CommunityToolKit.Mvvm v8.0.0
- Microsoft.Maui.Dependencies v6.0.536
- Microsoft.Maui.Extensions v6.0.536
- QuestPDF v2022.9.0
- SQLiteNetExtensions v2.1.0
- sqlite-net-pcl v1.8.116
- SQLitePCLRaw.bundle_green v2.1.2
- SQLitePCLRaw.core v2.1.2
- SQLitePCLRaw.lib.e_sqlite3 v2.1.2
- SQLitePCLRaw.provider.dynamic_cdecl v2.1.2
- System.Runtime.InteropServices.NFloat.Internal v6.0.1
- Microsoft.Windows.SDK.BuildTools v10.0.22000.194

**Comment by HenkVanMilligen** [comment]
Was there ever any resolution to this issue? Also experiencing a similar error when trying to save a pdf to internal storage on Android using .NET Maui Blazor Hybrid:

> "Could not resolve type with token 01000061 from typeref (expected class 'System.MemoryExtensions' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e')
[chromium]    at SkiaSharp.SKString..ctor(String str)
[chromium]    at SkiaSharp.SKString.Create(String str)
[chromium]    at SkiaSharp.SKDocument.CreatePdf(SKWStream stream, SKDocumentPdfMetadata metadata)
[chromium]    at SkiaSharp.SKDocument.CreatePdf(Stream stream, SKDocumentPdfMetadata metadata)
[chromium]    at QuestPDF.Drawing.PdfCanvas.CreatePdf(Stream stream, DocumentMetadata documentMetadata)
[chromium]    at QuestPDF.Drawing.PdfCanvas..ctor(Stream stream, DocumentMetadata documentMetadata)
[chromium]    at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
[chromium]    at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
[chromium]    at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
[chromium]    at RazorComponents.QuotepadInputs.GenerateQuoteOnClick() in 

Working fine when trying on Windows Machine.

**Comment by MarcinZiabek** [comment]
This looks like SkiaSharp issue. Maybe you are missing a Anddroid-specific dependency nuget for SkiaSharp? Or using incompatible versions?

**Comment by HenkVanMilligen** [comment]
Ah yes, you were correct thanks. After I updated to the latest version of SkiaSharp, the previous error seems to be resolved. So the SkiaSharp package that comes with the latest version of QuestPDF doesnt seem to be working with .NET Maui android. Thanks for responding so quick!

**Comment by YBTopaz8** [comment]
> Ah yes, you were correct thanks. After I updated to the latest version of SkiaSharp, the previous error seems to be resolved. So the SkiaSharp package that comes with the latest version of QuestPDF doesnt seem to be working with .NET Maui android. Thanks for responding so quick!

I'm curious to know please, what versions of SkiaSharp do you have installed as nuget please?
I have ;
- SkiaSharp.NativeAssets.Linux.NoDependencies
- SkiaSharp.NativeAssets.Android
- SkiaSharp 
all up to date, with QuestPDF itself being updated but I'm facing an issue still:

This one Specifically: 
![image](https://user-images.githubusercontent.com/41630728/200886836-3f64487a-55e6-4489-979a-eec9fb6b9dc2.png)

**Comment by YBTopaz8** [comment]
I see.
I tried the same, but to no avail. I can't blame my code because I just copied the basic example from the official website,
I can only blame the compiler or so?
Well, I'll keep scratching my head on it later.

**Comment by MarcinZiabek** [comment]
Unfortunately, as of the 2024.3.0 release, QuestPDF no longer supports the Android platform. This decision was made based on usage patterns but may be reevaluated in the future based on community feedback.

Since there has been no recent activity, I’m closing this issue. If you experience a similar problem or have a related request, feel free to open a new GitHub issue. I appreciate your feedback! ❤️
