### ISSUE TITLE
Cannot create the PDF document using the SkiaSharp-related library / Cannot load or decode provided image.

### ISSUE THREAD

**Issue by SuryaWalker** [QuestPDF/QuestPDF#456]
I have a  .net462 framework project where I am using questpdf 2022.12.1 to generate pdfs and its all working just fine locally on my pc, also when I publish it with clickonce and install locally, the application generates pdfs without any issue. But it does not work when installing the application on a different windows 10 machine with the same version of os. The following error message comes when trying to generate pdf. I checked the clickonce installation folder which is added per screenshot below and all the dlls are present inside that folder as expected but obviously some dependency or link between QuestPdf and SkiSharp is missing here. Locally I have Visual Studio 2022 installed with all the sdks, on the client machines only .net 6 and 7 runtimes. To workaround the issue I googled and added nuget references to NativeAssets.macOS, NativeAssets.Linux and NativeAssets.Linux.NoDependencies packages even though I am using Windows Platform but it doesn't help here.

QuestPDF.Drawing.Exceptions.InitializationException: Cannot create the PDF document using the SkiaSharp-related library. This exception usually means that, on your operating system where you run the application, SkiaSharp-related requires installing additional dependencies. Such dependencies are available as additional nuget packages, for example *.NativeAssets.Linux.NoDependencies. Some operating systems may require installing multiple nugets, e.g. MacOS may need both *.NativeAssets.macOS.NoDependencies and *.NativeAssets.Linux.NoDependencies.Please refer to the SkiaSharp-related documentation for more details. Also, please consult the inner exception that has been originally thrown by the dependency library. ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception. ---> System.DllNotFoundException: Unable to load library 'libSkiaSharp'.
   at SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName)
   at SkiaSharp.SkiaApi.<>c.<.cctor>b__1831_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at SkiaSharp.SkiaApi.sk_managedwstream_set_procs(SKManagedWStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedWStream..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKAbstractManagedWStream..ctor(Boolean owns)
   at SkiaSharp.SKDocument.CreatePdf(Stream stream, SKDocumentPdfMetadata metadata)
   at QuestPDF.Drawing.PdfCanvas.CreatePdf(Stream stream, DocumentMetadata documentMetadata)
   --- End of inner exception stack trace ---
   at QuestPDF.Drawing.PdfCanvas.CreatePdf(Stream stream, DocumentMetadata documentMetadata)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
  at button_click...
![image](https://user-images.githubusercontent.com/118480699/212903136-5a685edf-1144-4ee8-a2da-4a60be3d491a.png)
![image](https://user-images.githubusercontent.com/118480699/212907093-c40401a2-f7a5-49e5-87d8-6ee6cbde7b43.png)

After including of the folder x86\libSkiaSharp.dll, x86\libHarfBuzzSharp.dll the error message changes, now it says:

QuestPDF.Drawing.Exceptions.DocumentComposeException: Cannot load or decode provided image.
   at QuestPDF.Fluent.ImageExtensions.Image(IContainer parent, SKImage image, ImageScaling scaling)
   at JD.InterestBearing.Reporting.DealerReport.<ComposeHeader>b__9_1(RowDescriptor row)
   at QuestPDF.Fluent.RowExtensions.Row(IContainer element, Action`1 handler)
   at JD.InterestBearing.Reporting.DealerReport.<ComposeHeader>b__9_0(ColumnDescriptor col)
   at QuestPDF.Fluent.ColumnExtensions.Column(IContainer element, Action`1 handler)
   at JD.InterestBearing.Reporting.DealerReport.ComposeHeader(IContainer container)
   at QuestPDF.Fluent.ElementExtensions.Element[TParent](TParent parent, Action`1 handler)
   at JD.InterestBearing.Reporting.DealerReport.<Compose>b__8_1(PageDescriptor page)
   at QuestPDF.Fluent.PageExtensions.Page(IDocumentContainer document, Action`1 handler)
   at JD.InterestBearing.Reporting.DealerReport.Compose(IDocumentContainer c)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
...

**Comment by MarcinZiabek** [comment]
Good, it looks like you have added all required libraries 😁 

Please make sure that the image file is valid and truly available to your code. What file type is it?

**Comment by SuryaWalker** [comment]
oh, so obvious and so dumb 🤦‍♂️   Many thanks for pointing me into the right direction, the error message was doing that as well already 😄 , but I thought its related to some internal SKImage file handling... 👍
