### ISSUE TITLE
Cannot Create PDF "libSkiaSharp.dll" issue

### ISSUE THREAD

**Issue by mannapijush1coretech** [QuestPDF/QuestPDF#486]
Cannot able to create PDF . it's throws exception of 2 
1- SkiaSharp.SKAbstractManagedWStream
2 - DllNotFound 'libSkiaSharp.dll'

i am already tried to add references libSkiaSharp.dll manually then importing errors come
although already installed Skiasharp Native libraries (means 'libSkiaSharp.dll')

Here's is the Exception Trace

QuestPDF.Drawing.Exceptions.InitializationException
  HResult=0x80131500
  Message=Cannot create the PDF document using the SkiaSharp-related library. This exception usually means that, on your operating system where you run the application, SkiaSharp-related requires installing additional dependencies. Such dependencies are available as additional nuget packages, for example *.NativeAssets.Linux.NoDependencies. Some operating systems may require installing multiple nugets, e.g. MacOS may need both *.NativeAssets.macOS.NoDependencies and *.NativeAssets.Linux.NoDependencies.Please refer to the SkiaSharp-related documentation for more details. Also, please consult the inner exception that has been originally thrown by the dependency library.
  Source=QuestPDF
  StackTrace:
   at QuestPDF.Drawing.PdfCanvas.CreatePdf(Stream stream, DocumentMetadata documentMetadata)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at TensoLab.testOptions.kryptonButton1_Click(Object sender, EventArgs e) in C:\Users\Core Technologies\source\repos\TensoLab\TensoLab\testOptions.cs:line 48
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at ComponentFactory.Krypton.Toolkit.KryptonButton.OnClick(EventArgs e) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Toolkit\KryptonButton.cs:line 646
   at ComponentFactory.Krypton.Toolkit.KryptonButton.OnButtonClick(Object sender, MouseEventArgs e) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Toolkit\KryptonButton.cs:line 763
   at ComponentFactory.Krypton.Toolkit.ButtonController.OnClick(MouseEventArgs e) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controller\ButtonController.cs:line 912
   at ComponentFactory.Krypton.Toolkit.ButtonController.MouseUp(Control c, Point pt, MouseButtons button) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controller\ButtonController.cs:line 436
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 522
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 527
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 527
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewBase.cs:line 527
   at ComponentFactory.Krypton.Toolkit.ViewManager.MouseUp(MouseEventArgs e, Point rawPt) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\View Base\ViewManager.cs:line 511
   at ComponentFactory.Krypton.Toolkit.VisualControlBase.OnMouseUp(MouseEventArgs e) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Visuals\VisualControlBase.cs:line 968
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at ComponentFactory.Krypton.Toolkit.VisualControlBase.WndProc(Message& m) in D:\Github\Krypton\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Visuals\VisualControlBase.cs:line 1195
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at TensoLab.mainWindow.newTestMenuBtn_Click(Object sender, EventArgs e) in C:\Users\Core Technologies\source\repos\TensoLab\TensoLab\Form1.cs:line 199
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TensoLab.Program.Main() in C:\Users\Core Technologies\source\repos\TensoLab\TensoLab\Program.cs:line 19

Inner Exception 1:
TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.

Inner Exception 2:
DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Screenshots**
Here the ScreenShot of Method and References
![image](https://user-images.githubusercontent.com/85406239/218033007-f5e719bb-e132-4e60-88dc-18d5238b5118.png)

Please let me know if you want some other info

**Comment by mannapijush1coretech** [comment]
I found a solution that it's not related to the QuestPDF Library . Library depends on SkiaSharp APIs/DLL
although i have installed native skiasharp libraries the program is not detecting because --> 
 _My Application is Set to Debug Mode_ = **"Any CPU"**
i changed to that in x86 then i copied two dll 
1. libSkiaSharp.dll (from "_User Folder\.nuget\packages\skiasharp.nativeassets.win32\2.88.3\runtimes\win-x86\native_")
2. libHarfBuzzSharp.dll (from "_UserFolder\.nuget\packages\harfbuzzsharp.nativeassets.win32\2.8.2.3\runtimes\win-x86\native_")

**to bin folder of my application**
please make a note this error on your documentation if someone face this issue then they will know how to solve.

and thanks to you for this library as this is Lifesaving libraries for PDF Generation (specially for Generation APIs) as well as starred this project
and i am closing this issue now which is fixed
