### ISSUE TITLE
QuestPDF.Previewer does not work with dotnet 7 runtime.

### ISSUE THREAD

**Issue by luis-fss** [QuestPDF/QuestPDF#506]
**Is your feature request related to a problem? Please describe.**
QuestPDF.Previewer does not work with dotnet 7 runtime.

**Describe the solution you'd like**
QuestPDF.Previewer compatibility with dotnet 7 and also dotnet 6 runtimes.

**Describe alternatives you've considered**
If both runtimes are installed, dotnet 7 and dotnet 6, then QuestPDF.Previewer works normally.

**Additional context**
Keeping two versions of dotnet runtime installed may not be ideal in all cases.

**Comment by caseydierking** [comment]
I am also running into this issue. However I can't get the previewer working with .net 6 installed. I can launch the previewer, but it never shows the preview of the pdf i generate in code.

**Comment by MarcinZiabek** [comment]
I can build the QuestPDF.Preview nuget also for dotnet 7 runtime. However, there is one downside. Each platform target has its own folder with dependencies. So adding a second target will double nuget size, increasing it from 50 to 100 MB, which is significant. So we need to find a balance between forcing the developer to have a specific runtime available VS downloading a large nuget dotnet tool. This discussion will become even more significant once the dotnet 8 is available. 

What do you think?

**Comment by luis-fss** [comment]
You have a point. I thought about it for a while, but I couldn't come up with a good solution. What I concluded is that, if you have to choose, it is almost always a good practice to adopt the most recent version of a framework, after all QuestPDF.Preview for dotnet6 will always be available via nuget and bugfixes can occur if necessary.

**Comment by pennellarodrigo** [comment]
Any news?

**Comment by MarcinZiabek** [comment]
To the best of my knowledge, the current setup is entirely functional. Let me explain all the details:

1) For projects depending on QuestPDF, you have the complete flexibility to use any version of the dotnet platform. Even though only dotnet 6 and beyond versions support the hot-reload feature, you're not restricted. Whether it's upgrading to dotnet 7 now, or to dotnet 8 in the nearest future, the library does not hold you back.

2) The QuestPDF Previewer requires the dotnet 6 platform installed on your development machine. But here's the thing: the dotnet versions between the previewer and your project don't have to be identical. As previously mentioned, I could build distinct targets for each dotnet release, but it would double or triple the size of the nuget package (already over 50 MB).

I hope this provides some clarity 😀

**Comment by GrapeJuice787** [comment]
This doesn't run on .NET 8 either

**Comment by MarcinZiabek** [comment]
@ganiester, do you notice any exceptions when running the newest version of QuestPDF Previewer? What dotnet version are you using?

**Comment by ganiester** [comment]
<TargetFramework>net6.0</TargetFramework>, I don't recall any other exceptions. I do recall it working at first though. When I upgraded QuestPDF to the latest it worked initially but the next day it just gave me the grey screen.

**Comment by GrapeJuice787** [comment]
@girlpunk here is some additional information... 
SDK: .NET Core 8, specifically, `8.0.100`
Architecture/OS: M1 Mac

- Repro steps, follow instructions [here](https://www.questpdf.com/document-previewer.html)
  1. `dotnet tool install QuestPDF.Previewer --global`
  2. Run the application with the document
      ```
       document.ShowInPreviewer();
      ```

Result:
```
Unhandled exception. System.Exception: Cannot start the QuestPDF Previewer tool. Please install it by executing in terminal the following command: 'dotnet tool install --global QuestPDF.Previewer'.
   at QuestPDF.Previewer.PreviewerService.StartPreviewer()
   at QuestPDF.Previewer.PreviewerService.Connect()
   at QuestPDF.Previewer.Extensions.ShowInPreviewerAsync(IDocument document, Int32 port, CancellationToken cancellationToken)
   at QuestPDF.Previewer.Extensions.ShowInPreviewer(IDocument document, Int32 port)
   at Program.<Main>$(String[] args) in /Users/thomasa/Documents/Projects/QuestLocalPreviewer/Program.cs:line 47

Process finished with exit code 134.

```
