### ISSUE TITLE
System.DllNotFoundException: libHarfBuzzSharp when using QuestPDF in Blazor WASM

### ISSUE THREAD

**Issue by fingers10** [QuestPDF/QuestPDF#507]
@MarcinZiabek Many thanks for this wonderful library. I tried Using QuestPDF in Blazor but I'm getting error.

Steps:
1. Add Nuget Package
```xml
<PackageReference Include="QuestPDF" Version="2022.12.1" />
<PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.3" />
```
2.  Generate PDF in `Index.razor`.
```razor
@page "/"
@using QuestPDF.Drawing;
@using QuestPDF.Fluent;
@using QuestPDF.Helpers;
@inject HttpClient Http;

@if (Base64String is not null)
{
    <iframe src="@($"data:application/pdf;base64,{Base64String}")"></iframe>   
}

@code {
    protected string? Base64String { get; set; }

    private const string _font = "NotoSansSmall";

    protected async override Task OnInitializedAsync()
    //protected override void OnInitialized()
    {
        FontManager.RegisterFont(await Http.GetStreamAsync(@"http://localhost:5119/NotoSansSmall.ttf"));
        //FontManager.RegisterFont(File.OpenRead(@"NotoSansSmall.ttf"));

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.ContinuousSize(3, QuestPDF.Infrastructure.Unit.Inch);
                page.MarginVertical(5);
                page.MarginHorizontal(10);

                // page content
                page
                .Content()
                .AlignCenter()
                .Column(column =>
                {
                    column
                    .Item()
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Line("Address: https://ilovedotnet.org")
                            .Italic();
                        text.Line("Description: Interactive .NET Knowledge Sharing Platform with In Browser Demos");
                    });

                    column
                    .Item()
                    .LineHorizontal(1)
                    .LineColor(Colors.Grey.Medium);

                    column
                    .Item()
                    .PaddingTop(5)
                    .PaddingBottom(-10)
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Line("Abdul Rahman").Bold();
                    });

                    column
                    .Item()
                    .LineHorizontal(1)
                    .LineColor(Colors.Grey.Medium);

                    column
                    .Item()
                    .PaddingTop(5)
                    .PaddingBottom(-10)
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Line("Frequency: Weekly Once");
                        text.Line("Day: Every Sunday");
                        text.Line("Payment Mode: Free");
                        text.Line("Active Users: 1500+");
                        text.Line("Owned By: Abdul Rahman");
                        text.Line("Powered By: .NET");
                    });

                    column
                    .Item()
                    .LineHorizontal(1)
                    .LineColor(Colors.Grey.Medium);

                    column
                    .Item()
                    .PaddingVertical(10)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(8);
                            columns.RelativeColumn(2);
                        });

                        table.Cell().Text("Channel").Bold();
                        table.Cell().AlignRight().Text("Article Count").Bold();

                        table.Cell().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Medium);
                        table.Cell().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Medium);

                        table.Cell().Text("Total").Bold();
                        table.Cell().AlignRight().Text("58").Bold();
                    });

                    column
                    .Item()
                    .LineHorizontal(1)
                    .LineColor(Colors.Grey.Medium);

                    column
                    .Item()
                    .PaddingTop(10)
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Line("Thank you for reading");
                        text.Line("This is a computer generated receipt");
                        text.Line("This site is built by Bhai");
                        text.Line("And I Love .NET");
                    });
                });
            });
        });

        document.WithMetadata(new QuestPDF.Drawing.DocumentMetadata
            {
                Title = "Articles Summary",
                Author = "Abdul Rahman",
                Creator = "I Love .NET",
                PdfA = true
            });

        //Base64String = document.GenerateImages().First().ToString();

        using var memstream = new MemoryStream();
        document.GeneratePdf(memstream);
        Base64String = Convert.ToBase64String(memstream.ToArray());
    }
}
```

I get the following Error:

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: libHarfBuzzSharp
System.DllNotFoundException: libHarfBuzzSharp
   at HarfBuzzSharp.Buffer..ctor()
   at QuestPDF.Drawing.TextShaper.Shape(String text)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.MeasureWithoutCache(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.Measure(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.TextBlock.<DivideTextItemsIntoLines>g__GetNextLine|30_0(<>c__DisplayClass30_0& )
   at QuestPDF.Elements.Text.TextBlock.DivideTextItemsIntoLines(Single availableWidth, Single availableHeight)+MoveNext()
   at System.Collections.Generic.List`1[[QuestPDF.Elements.Text.Calculation.TextLine, QuestPDF, Version=2022.12.1.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TextLine](IEnumerable`1 source)
   at QuestPDF.Elements.Text.TextBlock.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Extend.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Elements.Decoration.PlanLayout(Size availableSpace)+MoveNext()
   at System.Collections.Generic.List`1[[QuestPDF.Elements.DecorationItemRenderingCommand, QuestPDF, Version=2022.12.1.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[DecorationItemRenderingCommand](IEnumerable`1 source)
   at QuestPDF.Elements.Decoration.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Padding.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Constrained.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Layers.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[FreeCanvas](PageContext pageContext, FreeCanvas canvas, Container content, DebuggingState debuggingState)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[PdfCanvas](PdfCanvas canvas, IDocument document)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at PDFBlazor.Pages.Index.OnInitializedAsync() in C:\Repos\PDFBlazor\PDFBlazor\Pages\Index.razor:line 147
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Please assist me on this. I'm planning to write an article showing usage of QuestPDF in blazor wasm. But got stuck with this issue.

_Originally posted by @fingers10 in https://github.com/QuestPDF/QuestPDF/discussions/261#discussioncomment-5080199_

**Comment by jgoday** [comment]
Hi @fingers10 I'm facing the same problem with '2022.12.2' version
```
<PackageReference Include="QuestPDF" Version="2022.12.2" />
```

Seems that Skia HarfBuzzSharp native library is missing,
I was able to fix it by including the following dependencies:
```
<ItemGroup>
  <NativeFileReference Include="$(HarfBuzzSharpStaticLibraryPath)/3.1.7/*.a" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="HarfBuzzSharp" Version="2.8.2.3" />
  <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="2.8.2.3" />
  <PackageReference Include="QuestPDF" Version="2022.12.2" />
  <PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.3" />
</ItemGroup>
```

**Comment by jgoday** [comment]
@fingers10 indeed, it should be located under
```
~/.nuget/packages/harfbuzzsharp.nativeassets.webassembly/2.8.2.3/build/netstandard1.0/libHarfBuzzSharp.a/3.1.7/libHarfBuzzSharp.a
```

**Comment by namtab00** [comment]
@MarcinZiabek shouldn't this also be documented [here in the official docs](https://www.questpdf.com/going-production/platform-specific-dependencies.html) ?

I've had to include these dependencies when deploying to a Docker container based on the `mcr.microsoft.com/dotnet/aspnet:6.0` image:

```
<PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="2.8.2.3" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.3" />
```

I was getting first an exception for missing `libSkiaSharp` then another one for missing `libHarfBuzzSharp`.

**Comment by jaygreina** [comment]
Wanted to add my two cents for those using Blazor WASM, .NET 7, and current version of QuestPDF 2023.10.2.
Based on @jgoday comments, I was still getting errors, but I was finally able to get things working after trying several combinations of libraries and versions. In addition to installing wasm-tools, the following is the minimum needed to get everything to work.
```
<ItemGroup>
  <NativeFileReference Include="$(HarfBuzzSharpStaticLibraryPath)/3.1.34/st/*.a" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="7.3.0" />
  <PackageReference Include="QuestPDF" Version="2023.10.2" />
  <PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.6" />
</ItemGroup>
```

**Comment by erbatista** [comment]
In a  Blazor 8 web app with interactivity Web Assembly I solved the problem by adding SkiaSharp.HarfBuzz and  SkiaSharp.NativeAssets.WebAssembly, not need to add the NativeFileReference mentioned above. 

For anyone wanting to save time, here are the packages references I have in my WebAssembly client project file:

```
      <PackageReference Include="QuestPDF" Version="2023.12.6" />
      <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="7.3.0.1" />
      <PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.7" />      
      <PackageReference Include="SkiaSharp.HarfBuzz" Version="2.88.7" />
      <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.88.7" />
```

**Comment by fingers10** [comment]
@erbatista yes I was able to make it work some weeks back with the similar setup you have shared... However when I execute the linux pipeline in GitHub Actions, I was getting some error related to missing packages. Here is the [run](https://github.com/ILoveDotNet/ilovedotnet/actions/runs/8130437635/job/22218633335) details.

```
Error: ROR] The HTTP status code was not OK. (it was (500)InternalServerError.)
      System.TypeInitializationException: The type initializer for 'QuestPDF.Fluent.Document' threw an exception.
       ---> QuestPDF.Drawing.Exceptions.InitializationException: The QuestPDF library has encountered an issue while loading one of its dependencies. This type of error often occurs when the current runtime is missing necessary NuGet packages. 
      
      Please ensure the following NuGet packages are added to your primary/startup project and has matching versions:
      - SkiaSharp.NativeAssets.Linux.NoDependencies
      - HarfBuzzSharp.NativeAssets.Linux
      
      For a detailed understanding, please examine the inner exception and consult the official SkiaSharp library documentation.
       ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
      /home/runner/.nuget/packages/blazorwasmprerendering.build/3.1.0-preview.4/tools/net8.0/.webhost/libSkiaSharp.so: cannot open shared object file: No such file or directory
      /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/libSkiaSharp.so: cannot open shared object file: No such file or directory
      /home/runner/.nuget/packages/blazorwasmprerendering.build/3.1.0-preview.4/tools/net8.0/.webhost/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
      /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
      /home/runner/.nuget/packages/blazorwasmprerendering.build/3.1.0-preview.4/tools/net8.0/.webhost/libSkiaSharp: cannot open shared object file: No such file or directory
      /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/libSkiaSharp: cannot open shared object file: No such file or directory
      /home/runner/.nuget/packages/blazorwasmprerendering.build/3.1.0-preview.4/tools/net8.0/.webhost/liblibSkiaSharp: cannot open shared object file: No such file or directory
      /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/liblibSkiaSharp: cannot open shared object file: No such file or directory
```

I tried adding missing packages but didn't work... Any hints or ideas in this?

**Comment by fingers10** [comment]
More details on Pipeline failure can be found here - https://github.com/ILoveDotNet/ilovedotnet/actions/runs/8408722502/job/23025207542?pr=245

**Comment by fingers10** [comment]
@jgoday were you able to run this in Github Actions Pipeline?

**Comment by MarcinZiabek** [comment]
Starting with the 2024.3.0 release, QuestPDF has removed its dependencies on SkiaSharp and HarfBuzzSharp, effectively resolving this problem on all platforms. However, this update also means that WASM support has been discontinued.

Since there has been no recent activity, I’m closing this issue. If you experience a similar problem or have a related request, feel free to open a new GitHub issue. I appreciate your feedback! ❤️
