### ISSUE TITLE
Calling `IContainer.Background(null)` throws a confusing exception

### ISSUE THREAD

**Issue by girlpunk** [QuestPDF/QuestPDF#528]
**Describe the bug**
When accidentally calling `IContainer.Background()` with a null colour value, the exception generated is not helpful in finding the cause of the issue.

**To Reproduce**
`IContainer.Background(null)`

**Expected behavior**
A more useful error message, preferably with a layout or stack trace

**Screenshots**
In my case the exception was:
```csharp
QuestPDF.Drawing.Exceptions.DocumentDrawingException: An exception occured during document drawing.
---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
at System.ThrowHelper.ThrowArgumentNullException(String name)
at System.ThrowHelper.ThrowKeyNullException()
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at QuestPDF.Drawing.FontManager.ColorToPaint(String color)
at QuestPDF.Drawing.SkiaCanvasBase.DrawRectangle(Position vector, Size size, String color)
at QuestPDF.Elements.Background.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Border.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Row.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Column.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Column.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Section.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Column.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Section.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Padding.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Column.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Layers.<>c__DisplayClass6_0.b__1(Layer x)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at QuestPDF.Elements.Layers.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Decoration.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Padding.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Constrained.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Layers.<>c__DisplayClass6_0.b__1(Layer x)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at QuestPDF.Elements.Layers.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Background.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Elements.Column.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Infrastructure.ContainerElement.Draw(Size availableSpace)
at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, Container content, DebuggingState debuggingState)
--- End of inner exception stack trace ---
at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, Container content, DebuggingState debuggingState)
at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document)
at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
at xxx.xxx.xxx.<>c__DisplayClass0_0.<b__0>d.MoveNext() in xxx.cs:line 42
--- End of stack trace from previous location ---
```

**Additional context**
Suggest resolving this by adding something like `ArgumentNullException.ThrowIfNull(value)` to the `Color` setter in `QuestPDF.Elements.Background`

**Comment by MarcinZiabek** [comment]
Great catch! 😁

What do you propose as a better behavior? So far I, see two options:
1) Throw an exception when the color argument is `null`
2) Or replace `null` with a default color, for background it should be most likely the `transparent` color.

**Comment by girlpunk** [comment]
Explicitly calling with null should probably be an exception imho

**Comment by MarcinZiabek** [comment]
> Explicitly calling with null should probably be an exception imho.

It depends but I certainly see your point. On the other hand, the `text` element replaces the `null` value with empty string. Hence the suggestion with `transparent` color. Or maybe, the `text` element behavior could be improved?

> Along similar lines, calling with an invalid colour generates a similarly confusing trace. I suspect this applies to other places colours are used, such as font colours and borders, as well.

Yes, I think so. Do you think it is essential to perform color validation as early as possible? Or can it be postponed until the generation process? The latter is simpler to implement but looses the stack trace and exact place where the incorrect color was passed as an argument, which may be valuable.

**Comment by MarcinZiabek** [comment]
Or, as an alternative, we can develop a family of flags, such as:

```csharp
Settings.ThrowExceptionWhenTextIsNull = true;
Settings.ThrowExceptionWhenColorIsNull = true;
Settings.ThrowExceptionWhenImageIsNull = true;
// etc.
```

The idea here is that we want to inform the developer about potential issues but also minimize the impact on production environments. I am not sure how useful such a solution would be.

**Comment by girlpunk** [comment]
> Do you think it is essential to perform color validation as early as possible

As long as a stack trace (not necessarily a layout trace) is available, troubleshooting should be significantly easier.

In terms of the impact on production, could the colours be checked earlier if debugging is enabled? That way the issue would be easier to troubleshoot in test environments without the performance overheads in production ones.

**Comment by MarcinZiabek** [comment]
Since version 2024.4, QuestPDF parses and validates content at the earliest stage, providing detailed exception messages to improve error detection and debugging.

Since there has been no recent activity, I’m closing this issue. If you have a similar request in the future, feel free to open a new GitHub issue. Thanks for your feedback! ❤️
