### ISSUE TITLE
Throws exception when running in Windows Nano Server container

### ISSUE THREAD

**Issue by neilrees** [QuestPDF/QuestPDF#54]
When running the example inside a Windows Nano Server container it throws `TypeInitializationException`, but it works inside Windows Server Core container.

When built using `mcr.microsoft.com/dotnet/runtime:5.0` as the base image the following exception is thrown:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SkiaSharp.SkiaApi.sk_managedwstream_set_procs(SKManagedWStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedWStream..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKAbstractManagedWStream..ctor(Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream, Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream)
   at SkiaSharp.SKDocument.CreatePdf(Stream stream, SKDocumentPdfMetadata metadata)
   at QuestPDF.Drawing.PdfCanvas..ctor(Stream stream, DocumentMetadata documentMetadata) in C:\Work\QuestPDF\QuestPDF\Drawing\PdfCanvas.cs:line 13
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document) in C:\Work\QuestPDF\QuestPDF\Drawing\DocumentGenerator.cs:line 19
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream) in C:\Work\QuestPDF\QuestPDF\Fluent\GenerateExtensions.cs:line 26
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath) in C:\Work\QuestPDF\QuestPDF\Fluent\GenerateExtensions.cs:line 21
   at QuestPDF.Examples.Engine.RenderingTest.Render(IDocument document) in C:\Work\QuestPDF\QuestPDF.Examples\Engine\RenderingTest.cs:line 109
   at QuestPDF.Examples.Engine.RenderingTest.RenderDocument(Action`1 content) in C:\Work\QuestPDF\QuestPDF.Examples\Engine\RenderingTest.cs:line 92
   at QuestPDF.Examples.Engine.RenderingTest.Render(Action`1 content) in C:\Work\QuestPDF\QuestPDF.Examples\Engine\RenderingTest.cs:line 72
   at QuestPDF.Examples.TextBenchmark.Generate() in C:\Work\QuestPDF\QuestPDF.Examples\TextBenchmark.cs:line 21
```

Same executables work when using `mcr.microsoft.com/dotnet/runtime:5.0-windowsservercore-ltsc2019` as the base image.

**Comment by MarcinZiabek** [comment]
It seems that this issue is not about QuestPDF itself but SkiaSharp. I suggest looking at the SkiaSharp repository to hopefully find an answer and share it with others 😀

**Comment by neilrees** [comment]
The SkiaSharp library does have some guidance on their Wiki regarding how to use SkiaSharp in nano server https://github.com/mono/SkiaSharp/wiki/WIP-Changelog

And updating the csproj to use these package references does address the above exception:

```
    <ItemGroup>
      <PackageReference Include="QuestPDF" Version="2021.11.4" ExcludeAssets="native"/>
      <PackageReference Include="SkiaSharp" Version="2.80.3" ExcludeAssets="native" />
      <PackageReference Include="SkiaSharp.NativeAssets.NanoServer" Version="2.80.3" />
    </ItemGroup>
```

However, now it hits another exception:
```
Unhandled exception. System.ArgumentException: The typeface Lucida Console could not be found.
   at QuestPDF.Drawing.FontManager.<ToPaint>g__GetTypeface|6_2(TextStyle style) in C:\Work\QuestPDF\QuestPDF\Drawing\FontManager.cs:line 57
   at QuestPDF.Drawing.FontManager.<ToPaint>g__Convert|6_1(TextStyle style) in C:\Work\QuestPDF\QuestPDF\Drawing\FontManager.cs:line 41
   at QuestPDF.Drawing.FontManager.<>c__DisplayClass6_0.<ToPaint>b__0(String key) in C:\Work\QuestPDF\QuestPDF\Drawing\FontManager.cs:line 37
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at QuestPDF.Drawing.FontManager.ToPaint(TextStyle style) in C:\Work\QuestPDF\QuestPDF\Drawing\FontManager.cs:line 37
   at QuestPDF.Elements.Text.Items.TextBlockSpan.MeasureWithoutCache(TextMeasurementRequest request) in C:\Work\QuestPDF\QuestPDF\Elements\Text\Items\TextBlockSpan.cs:line 31
   at QuestPDF.Elements.Text.Items.TextBlockPageNumber.Measure(TextMeasurementRequest request) in C:\Work\QuestPDF\QuestPDF\Elements\Text\Items\TextBlockPageNumber.cs:line 13
   at QuestPDF.Elements.Text.TextBlock.<DivideTextItemsIntoLines>g__GetNextLine|19_0(<>c__DisplayClass19_0& ) in C:\Work\QuestPDF\QuestPDF\Elements\Text\TextBlock.cs:line 174
   at QuestPDF.Elements.Text.TextBlock.DivideTextItemsIntoLines(Single availableWidth, Single availableHeight)+MoveNext() in C:\Work\QuestPDF\QuestPDF\Elements\Text\TextBlock.cs:line 139
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at QuestPDF.Elements.Text.TextBlock.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Text\TextBlock.cs:line 30
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.Padding.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Padding.cs:line 24
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.SimpleDecoration.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Decoration.cs:line 30
   at QuestPDF.Elements.SimpleDecoration.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Decoration.cs:line 36
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.Padding.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Padding.cs:line 24
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.Extend.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Extend.cs:line 14
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.Extend.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Extend.cs:line 14
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.SimpleDecoration.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Decoration.cs:line 36
   at QuestPDF.Elements.SimpleDecoration.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Decoration.cs:line 36
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.Padding.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Padding.cs:line 24
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.Constrained.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Constrained.cs:line 28
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Elements.Padding.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Elements\Padding.cs:line 24
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace) in C:\Work\QuestPDF\QuestPDF\Infrastructure\ContainerElement.cs:line 25
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, Container content, DocumentMetadata documentMetadata) in C:\Work\QuestPDF\QuestPDF\Drawing\DocumentGenerator.cs:line 59
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document) in C:\Work\QuestPDF\QuestPDF\Drawing\DocumentGenerator.cs:line 42
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document) in C:\Work\QuestPDF\QuestPDF\Drawing\DocumentGenerator.cs:line 20
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream) in C:\Work\QuestPDF\QuestPDF\Fluent\GenerateExtensions.cs:line 26
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath) in C:\Work\QuestPDF\QuestPDF\Fluent\GenerateExtensions.cs:line 21
   at QuestPDF.Examples.Engine.RenderingTest.Render(IDocument document) in C:\Work\QuestPDF\QuestPDF.Examples\Engine\RenderingTest.cs:line 109
   at QuestPDF.Examples.Engine.RenderingTest.RenderDocument(Action`1 content) in C:\Work\QuestPDF\QuestPDF.Examples\Engine\RenderingTest.cs:line 92
   at QuestPDF.Examples.Engine.RenderingTest.Render(Action`1 content) in C:\Work\QuestPDF\QuestPDF.Examples\Engine\RenderingTest.cs:line 72
   at QuestPDF.Examples.TextBenchmark.Generate() in C:\Work\QuestPDF\QuestPDF.Examples\TextBenchmark.cs:line 21
```

Which is another known issue to do with Font management in Nano server https://github.com/mono/SkiaSharp/issues/1105

So Windows Nano Server support seems blocked until that issue can be resolved.

**Comment by MarcinZiabek** [comment]
In such environments, you need to host your own font files and load them in the runtime. [Please take a look](https://www.questpdf.com/documentation/patterns-and-practices.html#support-for-the-linux-environment)

**Comment by neilrees** [comment]
Registering the font file does fix the exception, but the resultant PDF contains no rendered text:

![image](https://user-images.githubusercontent.com/282424/141837722-8fcb059f-8bfc-4bfa-9ded-6c7519c39059.png)

Left: Windows Server Core, Right: Windows Server Nano

**Comment by MarcinZiabek** [comment]
Thank you for testing. So... it looks like it is really an issue of SkiaSharp and there is not much we can do 😥

**Comment by cgohier** [comment]
Is this the issue?

https://github.com/mono/SkiaSharp/issues/1105

**Comment by neilrees** [comment]
> Which is another known issue to do with Font management in Nano server [mono/SkiaSharp#1105](https://github.com/mono/SkiaSharp/issues/1105)

Yes, that's the same issue.

**Comment by TealEgg** [comment]
Hello, I know this is late, but if anyone else has an issue like this and is using a Linux dis, use the SkiaSharp.NativeAssets.Linux.NoDependencies nuget package instead of the normal one. This fixes the System.TypeInitializationException.

**Comment by IsmailAlaouiAbdellaoui** [comment]
What do you mean by using it ? I installed it as a new dependency in my class library (both SkiaSharp.NativeAssets.Linux.NoDependencies and SkiaSharp.NativeAssets.Linux ) and it still does not work. Any help to make these installations being effective ? Thanks

**Comment by ekjuanrejon** [comment]
i have the same error. works in windows but not inside a docker container
`System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.\n ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory\n   at SkiaSharp.SkiaApi.sk_managedwstream_set_procs(SKManagedWStreamDelegates procs)\n   at SkiaSharp.SKAbstractManagedWStream..cctor()\n   --- End of inner exception stack trace ---\n   at SkiaSharp.SKAbstractManagedWStream..ctor(Boolean owns)\n   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream, Boolean owns)\n   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream)\n   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream)\n   at SkiaSharp.SKDocument.CreatePdf(Stream stream, SKDocumentPdfMetadata metadata)\n   at QuestPDF.Drawing.PdfCanvas..ctor(Stream stream, DocumentMetadata documentMetadata)\n   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)\n `

**Comment by girlpunk** [comment]
@ekjuanrejon Have you added the relevent `SkiaSharp.NativeAssets` NuGet package to your project?

**Comment by ekjuanrejon** [comment]
i added the following nupkg to docker and the pdf gets generated but is empty...

<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.3" />

let me try adding that other nupkg

**Comment by ekjuanrejon** [comment]
I tried the other nupkg and does not work..

System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory

**Comment by ekjuanrejon** [comment]
Working. I'll post fix later

**Comment by MarcinZiabek** [comment]
@ekjuanrejon That's great! Please do share the solution as it may be valuable for others. We may even put it within the documentation 😁

**Comment by ekjuanrejon** [comment]
Hello, 

I added the following to visual studio net6 project...
`<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.0-preview.209" />`

and the following to docker 
```
RUN sed -i'.bak' 's/$/ contrib/' /etc/apt/sources.list
RUN apt-get update; apt-get install -y ttf-mscorefonts-installer fontconfig
```

**Comment by neilrees** [comment]
@ekjuanrejon Looks like you're running on Linux not Windows Nano Server?

**Comment by JezzRDZ** [comment]
Any solution to this? 
Does anyone was able to make it work on nano server?

**Comment by MarcinZiabek** [comment]
Windows Nano Server is not a typical hosting environment for QuestPDF. Due to its low adoption, we do not plan to support it at this time. Closing this issue.
