### ISSUE TITLE
PDF with image: The process was terminated due to an unhandled exception

### ISSUE THREAD

**Issue by johnkors** [QuestPDF/QuestPDF#571]
**Describe the bug**
Generating a PDF containing a image, we see that it  _sometimes_  crashes the entire application and terminating the process. So far, the only time we see it is under load  testing(running a batch job with loads of PDFs being generated in the same process), but not immediatly. After reboot, it processes the PDF fine.

CPU/Memory are within acceptable values during this (10-20% CPU utilisation).

This is written as output to the Event Log

<details>
  <summary>Event log</summary>
  
```
Application: w3wp.exe CoreCLR Version: 7.0.523.17405 .NET Version: 7.0.5 
Description: The process was terminated due to an unhandled exception. 
Stack:
   at SkiaSharp.SkiaApi.sk_image_scale_pixels(IntPtr undefined, IntPtr undefined, SkiaSharp.SKFilterQuality undefined, SkiaSharp.SKImageCachingHint undefined)
   at QuestPDF.Helpers.Helpers.ResizeAndCompressImage(SkiaSharp.SKImage undefined, QuestPDF.Infrastructure.ImageSize undefined, QuestPDF.Infrastructure.ImageCompressionQuality undefined)
   at QuestPDF.Infrastructure.Image.GetVersionOfSize(QuestPDF.Infrastructure.GetImageVersionRequest undefined)
   at QuestPDF.Elements.Image.GetImageToDraw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Image.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDFing.Proxy.CacheProxy.Draw.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.AspectRatio.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDFing.Proxy.CacheProxy.Draw.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Padding.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDFing.Proxy.CacheProxy.Draw.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Row.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDFing.Proxy.CacheProxy.Draw.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Decoration.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDFing.Proxy.CacheProxy.Draw.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Padding.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDFing.Proxy.CacheProxy.Draw.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Constrained.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Layers+<>c__DisplayClass6_0.<Draw>b__1(QuestPDF.Elements.Layer undefined)
   at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ForEach(System.Action`1<System.__Canon> undefined)
   at QuestPDF.Elements.Layers.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Background.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDFing.Proxy.CacheProxy.Draw.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Elements.Column.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Infrastructure.ContainerElement.Draw(QuestPDF.Infrastructure.Size undefined)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](QuestPDF.Infrastructure.PageContext undefined, System.__Canon undefined, QuestPDF.Elements.Container undefined, QuestPDF.Drawing.Proxy.DebuggingState undefined)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon undefined, QuestPDF.Infrastructure.IDocument undefined, QuestPDF.Infrastructure.DocumentSettings undefined)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(System.IO.Stream undefined, QuestPDF.Infrastructure.IDocument undefined)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(QuestPDF.Infrastructure.IDocument undefined) …
   
   Rest of stack trace omitted
```

</details>

**To Reproduce**

How we use the image API:

```csharp
void ComposeFooter(IContainer container)
{
    container.Row(row =>
    {
        row.ConstantItem(100)
            .Padding(10)
            .Image(_logoPath);
    });
}
```                        

The image loaded is a 66KB png.

**Expected behavior**
No crash.

**Screenshots**
Not relevant.

**Additional context**
Running on Azure App Service on a Windows app service plan:

- CoreCLR Version: 7.0.523.17405 .NET Version: 7.0.5 Description: 
- .NET Core 7 
- PDFs generated via background jobs in Hangfire
- QuestPDF version: 2023.5.0

**Comment by MarcinZiabek** [comment]
Hi 😁 

I cannot reproduce this issue. Would you please share more details about the stress test: 
- how many threads/tasks are used,
- is the image cached (e.g., via static property) and reused across many documents,
- how often does this problem happen,
- how long on average do you need to wait till the generation starts failing,
- is the stress test generating documents of the same type.

**Comment by johnkors** [comment]
In addition to the above, Azure Diagnostics says `1 crash due to (0xC0000005 - Native Access Violation)` when this happens. 


- We're running a maximum of 3 concurrent pdfs being generated via max limits in Hangfire queues. So it's not a likely bottleneck. CPU is also fine throughout.
- See API usage in OP, we just provide the path to a file on disk. If Quest caches that file internally, I have no idea.
- It consistently happens after 200 pdfs being generated (3 minutes). 
- Yes, it's generating documents of the same type

Sure, I'll try to upgrade to 2023.5.1.

**Comment by MarcinZiabek** [comment]
I understand that the logo file is always in the storage, right? Just a static file? Nothing generated/replaced during the runtime?

**Comment by johnkors** [comment]
Yeah, local file image deployed with the app. Nothing generated.

2023.5.1 did not seem to have the same issues, from my brief test 👍 I'll close it, and re-open if we see it with this version later. 

Btw, is it better if I create an image with the exact size? Will that remove the need for `ResizeAndCompressImage` being called internally? Other aspects of working with image that would be more efficient?

**Comment by MarcinZiabek** [comment]
> Btw, is it better if I create an image with the exact size? Will that remove the need for ResizeAndCompressImage being called internally? Other aspects of working with image that would be more efficient?

It depends. For your logo image, I recommend creating a global and static `Image` object, similar to this example: https://www.questpdf.com/api-reference/image.html#reusing-images-in-document The library will perform the scaling operation once, and then cache its result. This way, you can achieve the best performance possible.

You can also override global library/document settings by using the following API call. In such a case, the library will not scale nor compress the image:

```csharp
.Width(24)
.Image(image)
.UseOriginalImage();
```

**Comment by mg-pl** [comment]
> 
> ```cs
> .Width(24)
> .Image(image)
> ```
If `image` here is  `QuestPDF.Infrastructure.Image` then the examples do not compile because that overload is `internal`.

**Comment by blogcraft** [comment]
Image only recieves Byte[], string or Stream. No Image type.

        public static ImageDescriptor Image(this IContainer parent, byte[] imageData);
        public static ImageDescriptor Image(this IContainer parent, string filePath);
        public static ImageDescriptor Image(this IContainer parent, Stream fileStream);

So this example never compiles.

    var image = Image.FromFile("checkbox.png");
    
    foreach (var i in Enumerable.Range(0, 5))
    {
        column.Item().Row(row =>
        {
            row.AutoItem().Width(24).Image(image);
            row.RelativeItem().PaddingLeft(8).AlignMiddle().Text(Placeholders.Label()).FontSize(16);
        });
    }

**Comment by MarcinZiabek** [comment]
Thank you for noticing this issue! The aforementioned method should be indeed public. I will release a new release later today 😁

**Comment by johnkors** [comment]
Enabling `UseOriginalImage()` seems to fix app crashes, or at least we haven't seen them since adding that.

**Comment by MarcinZiabek** [comment]
> Enabling `UseOriginalImage()` seems to fix app crashes, or at least we haven't seen them since adding that.

Have you observed any crashes after upgrading to the `2023.5.2` version but without the `UseOriginalImage` option?

**Comment by johnkors** [comment]
Yeah, we saw crashes with `2023.5.2` as well.

**Comment by MarcinZiabek** [comment]
Would you please share more details about the following:
1) Your stress-testing methodology (level of parallelism, size of the document, number of images, typical time to generate PDF),
2) Does the crash happen when loading the image from the file, e.g.: `.Padding(10).Image("myFile.jpg");`
3) Does the crash always happen for the same image?
4) Does it happen at the very beginning of the test or somewhere in the middle? Did you observe any patterns?

I am determined to fix this problem.
Thank you 😁

**Comment by johnkors** [comment]
Sure, hope this helps:

> Your stress-testing methodology (level of parallelism, size of the document, number of images, typical time to generate PDF),

It wasn't that heavy of a load, really. We used Hangfire to queue up PDF a couple of hundred PDF generation jobs using 3 concurrent workers. This means, at any point in time, there would be a maximum of 3 concurrent PDFs being generated. 

>. Does the crash happen when loading the image from the file, e.g.: .Padding(10).Image("myFile.jpg");

Not sure what you mean by _when_ , but yes that's how we use the image API and observe crashes.

>Does the crash always happen for the same image?

The same image from file is used throughout.

> Does it happen at the very beginning of the test or somewhere in the middle? Did you observe any patterns?

I'd say beginning-ish. Looks like it's able to generate a certain amount (50-100 ish?), and then it crashes the w3wp process in Azure.

**Comment by johnkors** [comment]
Another thing we noticed is that `UseOrignalImage()` was 5x slower pr PDF:

![snip kjfTrvd6@2x](https://github.com/QuestPDF/QuestPDF/assets/206726/491a9117-78ad-4f21-8156-62dddd8fb774)

**Comment by MarcinZiabek** [comment]
Is this performance problem with the `UseOrignalImage()` option only related to one logo image? Or was it applied to other images as well? What are their resolutions?

**Comment by MarcinZiabek** [comment]
Using a similar technique as in https://github.com/QuestPDF/QuestPDF/issues/583, I also can not reproduce the crashing problem with a level of parallelism of 160 (16-core CPU) and 100 test batches. I do not observe any memory leaks or performance regressions. Would you please share a minimal example that causes the exception?
