### ISSUE TITLE
The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.

### ISSUE THREAD

**Issue by MarkusG** [QuestPDF/QuestPDF#62]
**Describe the bug**
When attempting to generate a PDF, the exception in the title is thrown.

**To Reproduce**
```cs
var document = new MyDocument();
document.GeneratePdf("mypath.pdf");
```

**Expected behavior**
The PDF document should get generated and written to the disk.

**Screenshots**
N/A

**Additional context**
The exact models used that generated this bug:

```cs
    public class ReportDataSource
    {
        private static Random _random = new Random();
        
        public static ReportModel GetReportDetails()
        {
            var profiles = Enumerable
                .Range(1, 8)
                .Select(i => GenerateRandomProfile())
                .ToList();

            return new ReportModel
            {
                CustomerName = Placeholders.Name(),
                ProfileEntries = profiles,
                Timestamp = DateTime.UtcNow
            };
        }

        private static ProfileEntry GenerateRandomProfile()
        {
            return new ProfileEntry
            {
                Name = Placeholders.Label(),
                Quantity = _random.Next(1, 100)
            };
        }
    }
```

```cs
    public class ReportDocument : IDocument
    {
        public ReportModel Model { get; }

        public ReportDocument(ReportModel model)
        {
            Model = model;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
        
        public void Compose(IDocumentContainer container)
        {
            container
                .Page(page =>
                {
                    page.Margin(50);

                    page.Header().Element(ComposeHeader);
                    page.Content().Element(ComposeContent);
                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.CurrentPageNumber();
                        x.Span(" / ");
                        x.TotalPages();
                    });
                });
        }

        private void ComposeHeader(IContainer container)
        {
            var titleStyle = TextStyle.Default.Size(20).SemiBold().Color(Colors.Blue.Medium);
            
            container.Row(row =>
            {
                row.RelativeColumn().Stack(stack =>
                {
                    stack.Item().Text($"Report on {Model.Timestamp}", titleStyle);
                    
                    stack.Item().Text(text =>
                    {
                        text.Span(Model.CustomerName, TextStyle.Default.SemiBold());
                    });
                });
                
                row.ConstantColumn(100).Height(50).Placeholder();
            });
        }

        private void ComposeContent(IContainer container)
        {
            container.PaddingTop(10).Decoration(decoration =>
            {
                decoration.Header().BorderBottom(1).Padding(5).Row(row =>
                {
                    row.ConstantColumn(25).Text("#");
                    row.RelativeColumn(3).Text("Product");
                    row.RelativeColumn().AlignRight().Text("Quantity");
                });

                decoration
                    .Content()
                    .Stack(stack =>
                    {
                        foreach (var profile in Model.ProfileEntries)
                        {
                            stack.Item().BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(5).Row(row =>
                            {
                                row.ConstantColumn(25).Text(Model.ProfileEntries.IndexOf(profile) + 1);
                                row.RelativeColumn(3).Text(profile.Name);
                                row.RelativeColumn().AlignRight().Text(profile.Quantity.ToString());
                            });
                        }
                    });
            });
        }
    }
```

```cs
    public class ReportModel
    {
        public DateTime Timestamp { get; set; }
        
        public string CustomerName { get; set; }
        
        public List<ProfileEntry> ProfileEntries { get; set; }
    }

    public class ProfileEntry
    {
        public string Name { get; set; }
        
        public int Quantity { get; set; }
    }
```

Exact stack trace:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_managedwstream_set_procs(SKManagedWStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedWStream..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKAbstractManagedWStream..ctor(Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream, Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream)
   at SkiaSharp.SKDocument.CreatePdf(Stream stream, SKDocumentPdfMetadata metadata)
   at QuestPDF.Drawing.PdfCanvas..ctor(Stream stream, DocumentMetadata documentMetadata)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at <my invoking code>
```

The preceding three classes are contained in a .NET Standard 2.1 class library, and the invoking code is in a .NET 5 app. It is also likely worth noting that this is occurring on Linux.

**Comment by MarcinZiabek** [comment]
Please take a look at [this article in the documentation](https://www.questpdf.com/documentation/patterns-and-practices.html#support-for-custom-environments-cloud-linux) and let me know if it helps :)

**Comment by MarkusG** [comment]
Installing `SkiaSharp.NativeAssets.Linux.NoDependencies` resolved the exception but led to mangled document output. Installing `SkiaSharp.NativeAssets.Linux` solves the problem. Thanks!

**Comment by OstapFilipenko** [comment]
@MarkusG @MarcinZiabek  After installing those 2 packages (SkiaSharp.NativeAssets.Linux.NoDependencies and SkiaSharp.NativeAssets.Linux) on my linux server the document generation worked without any errors for me
