### ISSUE TITLE
QuestPDF.Drawing.Exceptions.InitializationException: Cannot create the PDF document using the SkiaSharp-related library.

### ISSUE THREAD

**Issue by Ruitjes** [QuestPDF/QuestPDF#685]
**Describe the bug**
I've found some thread already about this bug, but even with installing all the packages I'm not able to create PDF's. 
Few days ago it just worked without adding any of these libraries, but yesterday I deployed the application on (render.com) where I had to add `SkiaSharp.NativeAssets.Linux.NoDependencies`, because I received the exact same code there as now.  I'm using the latest and greatest QuestPDF version (2023.10.0) downgrading to a lower version (2023.9.1) solves this issue.
I'm on my MacOS M1 Pro and I've tried a mix of these packages already:

`SkiaSharp.NativeAssets.Linux v2.88.6` & `SkiaSharp.NativeAssets.Linux.NoDependencies v2.88.6`
`SkiaSharp.NativeAssets.macOS v2.88.6`
`HarfBuzzSharp.NativeAssets.Linux v7.3.0` 
`HarfBuzzSharp.NativeAssets.macOS v7.3.0`

I've also looked at the referred package `*.NativeAssets.macOS.NoDependencies` but that one doesn't even seem to exists.

The error:

The full strace:

```
QuestPDF.Drawing.Exceptions.InitializationException: Cannot create the PDF document using the SkiaSharp-related library. This exception usually means that, on your operating system where you run the application, SkiaSharp-related requires installing additional dependencies. Such dependencies are available as additional nuget packages, for example *.NativeAssets.Linux.NoDependencies. Some operating systems may require installing multiple nugets, e.g. MacOS may need both *.NativeAssets.macOS.NoDependencies and *.NativeAssets.Linux.NoDependencies.Please refer to the SkiaSharp-related documentation for more details. Also, please consult the inner exception that has been originally thrown by the dependency library.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedWStream' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/libSkiaSharp.dylib, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/libSkiaSharp.dylib' (fcntl(fd, F_ADDFILESIGS_RETURN) failed with errno=37, sliceOffset=0x007F4000, codeBlobOffset=0x006C9050, codeBlobSize=0x0001A930 for '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/libSkiaSharp.dylib'), '/usr/local/lib/libSkiaSharp.dylib' (no such file), '/usr/lib/libSkiaSharp.dylib' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libSkiaSharp.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libSkiaSharp.dylib' (no such file), '/usr/local/lib/libSkiaSharp.dylib' (no such file), '/usr/lib/libSkiaSharp.dylib' (no such file)
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/libSkiaSharp.dylib, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/libSkiaSharp.dylib' (no such file), '/usr/local/lib/libSkiaSharp.dylib' (no such file), '/usr/lib/libSkiaSharp.dylib' (no such file)
dlopen(libSkiaSharp.dylib, 0x0001): tried: 'libSkiaSharp.dylib' (no such file), '/usr/local/lib/libSkiaSharp.dylib' (no such file), '/usr/lib/libSkiaSharp.dylib' (no such file), '/Users/..../Repositorys/....-mono/..../Backend/4 API/libSkiaSharp.dylib' (no such file), '/usr/local/lib/libSkiaSharp.dylib' (no such file), '/usr/lib/libSkiaSharp.dylib' (no such file)
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/liblibSkiaSharp.dylib, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/liblibSkiaSharp.dylib' (no such file), '/usr/local/lib/liblibSkiaSharp.dylib' (no such file), '/usr/lib/liblibSkiaSharp.dylib' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/liblibSkiaSharp.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/liblibSkiaSharp.dylib' (no such file), '/usr/local/lib/liblibSkiaSharp.dylib' (no such file), '/usr/lib/liblibSkiaSharp.dylib' (no such file)
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/liblibSkiaSharp.dylib, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/liblibSkiaSharp.dylib' (no such file), '/usr/local/lib/liblibSkiaSharp.dylib' (no such file), '/usr/lib/liblibSkiaSharp.dylib' (no such file)
dlopen(liblibSkiaSharp.dylib, 0x0001): tried: 'liblibSkiaSharp.dylib' (no such file), '/usr/local/lib/liblibSkiaSharp.dylib' (no such file), '/usr/lib/liblibSkiaSharp.dylib' (no such file), '/Users/..../Repositorys/....-mono/..../Backend/4 API/liblibSkiaSharp.dylib' (no such file), '/usr/local/lib/liblibSkiaSharp.dylib' (no such file), '/usr/lib/liblibSkiaSharp.dylib' (no such file)
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/libSkiaSharp, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/libSkiaSharp' (no such file), '/usr/local/lib/libSkiaSharp' (no such file), '/usr/lib/libSkiaSharp' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libSkiaSharp, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libSkiaSharp' (no such file), '/usr/local/lib/libSkiaSharp' (no such file), '/usr/lib/libSkiaSharp' (no such file)
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/libSkiaSharp, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/libSkiaSharp' (no such file), '/usr/local/lib/libSkiaSharp' (no such file), '/usr/lib/libSkiaSharp' (no such file)
dlopen(libSkiaSharp, 0x0001): tried: 'libSkiaSharp' (no such file), '/usr/local/lib/libSkiaSharp' (no such file), '/usr/lib/libSkiaSharp' (no such file), '/Users/..../Repositorys/....-mono/..../Backend/4 API/libSkiaSharp' (no such file), '/usr/local/lib/libSkiaSharp' (no such file), '/usr/lib/libSkiaSharp' (no such file)
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/liblibSkiaSharp, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/runtimes/osx/native/liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/liblibSkiaSharp, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file)
dlopen(/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/liblibSkiaSharp, 0x0001): tried: '/Users/..../Repositorys/....-mono/..../Backend/4 API/bin/Debug/net7.0/liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file)
dlopen(liblibSkiaSharp, 0x0001): tried: 'liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file), '/Users/..../Repositorys/....-mono/..../Backend/4 API/liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file)

   at SkiaSharp.SkiaApi.sk_managedwstream_set_procs(SKManagedWStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedWStream..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKAbstractManagedWStream..ctor(Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream, Boolean owns)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream, Boolean disposeManagedStream)
   at SkiaSharp.SKManagedWStream..ctor(Stream managedStream)
   at SkiaSharp.SKDocument.CreatePdf(Stream stream, SKDocumentPdfMetadata metadata)
   at QuestPDF.Drawing.PdfCanvas.CreatePdf(Stream stream, DocumentMetadata documentMetadata, DocumentSettings documentSettings)
   --- End of inner exception stack trace ---
   at QuestPDF.Drawing.PdfCanvas.CreatePdf(Stream stream, DocumentMetadata documentMetadata, DocumentSettings documentSettings)
   at QuestPDF.Drawing.PdfCanvas..ctor(Stream stream, DocumentMetadata documentMetadata, DocumentSettings documentSettings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
   at Services.TicketService.GenerateTicketPdf(List`1 ticketData) in /Users/..../Repositorys/....-mono/..../Backend/2 Services/TicketService.cs:line 47
   at API.Controllers.TicketController.GenerateAndSendTicketsByEmail(String bundleNumber) in /Users/..../Repositorys/....-mono/..../Backend/4 API/Controllers/TicketController.cs:line 38
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:5289
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7
Authorization: test
Cookie: __zlcmid=1I1m9JT9WUOAUAY
Origin: http://localhost:5289
Referer: http://localhost:5289/swagger/index.html
Content-Length: 0
sec-ch-ua: "Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
```

**Comment by MarcinZiabek** [comment]
I am working on MacOS as well (M2). I don't need to install any dependencies. The implicitly installed nugets seem to be the same as yours:

<img width="401" alt="image" src="https://github.com/QuestPDF/QuestPDF/assets/9263853/73e4dc6e-b863-42b8-aea1-d80b6d5e323d">

The 2023.10 release has bumped the SkiaSharp dependency from 2.88.3 to 2.88.6. Is there any chance you are fighting with local nuget/build cache?

**Comment by MarcinZiabek** [comment]
Since the 2024.3.0 release, QuestPDF no longer depends on SkiaSharp and HarfBuzzSharp. As a result, this issue has been resolved.

I’m closing this issue due to inactivity. If you encounter a similar issue or have a related request, please feel free to open a new GitHub issue. Thank you for your feedback! ❤️
