### ISSUE TITLE
Problem with QuestPDF on Ubuntu 22.04

### ISSUE THREAD

**Issue by DeafMan1983** [QuestPDF/QuestPDF#686]
Hello, 

I have watched Youtube by Nick Chapsas,

I followed it.
```
using ...

QuestPDF.Settings.License = LicenseType.Community;

Document.Create(container =>
{
    container.Page(page =>
    {
        
    });
})
.ShowInPreviewer();
```
Then I compile and preview.
That is lair because Nick Chapsas did shows preview with blank page. Why does it not happen with me?
It throws errors cause I use Ubuntu 22.04
```
dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'QuestPDF.Drawing.FontManager' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.7.23375.6/libSkiaSharp.so: cannot open shared object file: No such file or directory
/home/jens/Documents/TestPDF/bin/Debug/net8.0/libSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.7.23375.6/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/home/jens/Documents/TestPDF/bin/Debug/net8.0/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.7.23375.6/libSkiaSharp: cannot open shared object file: No such file or directory
/home/jens/Documents/TestPDF/bin/Debug/net8.0/libSkiaSharp: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.7.23375.6/liblibSkiaSharp: cannot open shared object file: No such file or directory
/home/jens/Documents/TestPDF/bin/Debug/net8.0/liblibSkiaSharp: cannot open shared object file: No such file or directory

   at SkiaSharp.SkiaApi.sk_data_new_empty()
   at SkiaSharp.SKData..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKData.Create(Stream stream)
   at QuestPDF.Drawing.FontManager.RegisterFont(Stream stream)
   at QuestPDF.Drawing.FontManager.RegisterLibraryDefaultFonts()
   at QuestPDF.Drawing.FontManager..cctor()
   --- End of inner exception stack trace ---
   at QuestPDF.Drawing.FontManager.ToTextShaper(TextStyle style)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.MeasureWithoutCache(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.Items.TextBlockSpan.Measure(TextMeasurementRequest request)
   at QuestPDF.Elements.Text.TextBlock.<DivideTextItemsIntoLines>g__GetNextLine|30_0(<>c__DisplayClass30_0&)
   at QuestPDF.Elements.Text.TextBlock.DivideTextItemsIntoLines(Single availableWidth, Single availableHeight)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at QuestPDF.Elements.Text.TextBlock.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Row.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Row.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Padding.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.ShowOnce.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Elements.Decoration.<PlanLayout>g__GetDecorationMeasurement|20_0(Element element, <>c__DisplayClass20_0&)
   at QuestPDF.Elements.Decoration.PlanLayout(Size availableSpace)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at QuestPDF.Elements.Decoration.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Padding.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.CacheProxy.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Constrained.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Layers.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, ContainerElement content)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePreviewerContent(IDocument document)
   at QuestPDF.Previewer.Extensions.<>c__DisplayClass1_0.<ShowInPreviewerAsync>g__GetPictures|4()
   at QuestPDF.Previewer.Extensions.<>c__DisplayClass1_0.<ShowInPreviewerAsync>g__RefreshPreview|2()
   at QuestPDF.Previewer.Extensions.ShowInPreviewerAsync(IDocument document, Int32 port)
   at QuestPDF.Previewer.Extensions.ShowInPreviewer(IDocument document, Int32 port)
   at Program.<Main>$(String[] args) in /home/jens/Documents/TestPDF/Program.cs:line 7
```
And where is loaded blank page inside Previewer?
![image](https://github.com/QuestPDF/QuestPDF/assets/57066679/e172cd3e-1066-4def-ae98-90c7a873471d)

I hope I have successful for Linux/BSD.

**Comment by MarcinZiabek** [comment]
Thank you for sharing this problem with us.

I am working on a better way to communicate the exact problem and which nuget packages are required. It seems that recent SkiaSharp releases are slightly more problematic.

Please try the following packages:
SkiaSharp.NativeAssets.Linux.NoDependencies 2.88.6
HarfBuzzSharp.NativeAssets.Linux 2.88.6

**Comment by MarcinZiabek** [comment]
Technically, we have code that should provide more detailed exceptions and point you to the proper package (https://github.com/QuestPDF/QuestPDF/blob/main/Source/QuestPDF/Drawing/Exceptions/InitializationException.cs). For some reason, it has stopped working recently after SkiaSharp update.

**Comment by MarcinZiabek** [comment]
Previewer is available as a global dotnet tool, and can be started with the following command: `questpdf-previewer`

If the Previewer instance is unavailable, c# code will attempt to start a new one automatically, assuming you have the necessary privileges to start a new terminal process.

**Comment by DeafMan1983** [comment]
Thanks for explanation! I will continue it.
