### ISSUE TITLE
PDF Generation Hangs in debug when producing an infinite layout

### ISSUE THREAD

**Issue by girlpunk** [QuestPDF/QuestPDF#751]
**Describe the bug**
After upgrading to QuestPDF 2023.12.2 (note that I'm upgrading from 2022.x so this might not be relevant) I have found a data file for my application which does not output a document.
When running with `QuestPDF.Settings.EnableDebugging` set to false, I receive an exception about the layout (which for the purposes of this bug, is expected behaviour) however when set to true the `IDocument.GeneratePdf()` call hangs and does not return a PDF with errors highlighted as expected.
The document takes approximately 30 seconds to error, and I have allowed several hours of hanging.

**To Reproduce**
I am unsure what precisely is causing this, as other invalid documents generate the PDF as expected.

**Expected behavior**
Either an exception should be thrown, or a PDF with layout issues highlighted should be returned

**Screenshots**
N/A

**Environment**
QuestPDF 2023.12.2
Windows 11 21H2 x64

**Additional context**
N/A

**Comment by MarcinZiabek** [comment]
Indeed, the expectation is that every layout constraint will be loosened enough to allow generating pages with annotated problematic places. Would you please share the code that you believe causes the problem?

**Comment by girlpunk** [comment]
I'm not too sure what in the code would be causing the problem. Unfortunately the document is around 200 pages long and the source code is similarly complex to match.

Is there any logging that could be enabled to show whereabouts in the document (even just with a stack trace) a layout constraint is being loosened?

**Comment by MarcinZiabek** [comment]
Are you using Dynamic components by any chance?

**Comment by girlpunk** [comment]
Nope, not used at all

**Comment by MarcinZiabek** [comment]
I have improved the algorithm that traverses the document's tree to detect layout issues and their exact location. Hopefully, the `2023.12.3` version will solve your issue. Would you please try it? 😀

**Comment by girlpunk** [comment]
After upgrading to `2023.12.3`, no change unfortunately. Same thing with `2023.12.3`.

**Comment by MarcinZiabek** [comment]
Thank you for testing!

Too bad... I will investigate the detection algorithm once more. Also, I will do my best to re-introduce the concept of layout trace in the next minor version soon.

**Comment by MarcinZiabek** [comment]
I made the last attempt to fix this algorithm. Honestly, I understand this problem better than ever now. I even left comments: https://github.com/QuestPDF/QuestPDF/blob/main/Source/QuestPDF/Drawing/Proxy/Helpers.cs#L51 But will it be enough? Please try it 😄

If your layout problem repeats on many pages (e.g., as part of the repeating content), you may expect generation time to be up to 5 times slower. There is some area for optimization, though. 

Also, the next significant thing on the roadmap, after the custom-skia-build effort, is the QuestPDF Previewer/Companion. A proper prerequisite will be to reintroduce layout logs.

**Comment by girlpunk** [comment]
Was that included as part of 2023.12.6? If so, I'm still seeing the issue unfortunately.

I've tried to test with 2024.3.0-alpha, however given the significant level of changes required to upgrade I wasn't able to get a useful answer. (`IContainer.Canvas()` deprecation will be a big one, as there are quite a number of graphs using this with LiveCharts2, and replacing all of them with placeholders to test gives an InvalidOperationException somewhere deep in the layout measurement).

**Comment by MarcinZiabek** [comment]
It has been a while since my last attempt to solve this issue. I am very sorry for not taking further action to fix it.

Currently, I am working on the enhanced layout debugging experience, which should provide more details and context. I would like to release it next week as part of the 2024.6.0 update.

Branch: https://github.com/QuestPDF/QuestPDF/tree/feat-enhanced-layout-issue-debugging

It is not finished yet, but I expect an exception message similar to this one:

```
The provided document content contains conflicting size constraints. For example, some elements may require more space than is available. 

To quickly determine the place where the problem is likely occurring, please generate the document with the attached debugger. The library will generate a PDF document with visually annotated places where layout constraints are invalid. 


The problem is likely located in:

-> Document

-> Page

-> Page content

-> In method:   ComposeContent
   Called from: Compose
   Source path: /Users/marcinziabek/RiderProjects/QuestPDF/Source/QuestPDF.ReportSample/Layouts/StandardReport.cs
   Line number: 40

-> PhotoTemplate

-> In method:   PhotoDetails
   Called from: Compose
   Source path: /Users/marcinziabek/RiderProjects/QuestPDF/Source/QuestPDF.ReportSample/Layouts/PhotoTemplate.cs
   Line number: 25


Please explore the layout trace for that location:

 🔴 ShowEntire
 ==============
 Available Space: (Width: 495,400, Height: 427,300)
 Space Plan: Wrap
 --------------


    🔴 Border
    ==========
    Available Space: (Width: 495,400, Height: 427,300)
    Space Plan: Wrap
    ----------
    Color: #9E9E9E
    Top: 0,75
    Right: 0,75
    Bottom: 0,75
    Left: 0,75


       🔴 Column
       ==========
       Available Space: (Width: 495,400, Height: 427,300)
       Space Plan: Wrap
       ----------


          🔴 Row
          =======
          Available Space: (Width: 495,400, Height: 427,300)
          Space Plan: Wrap
          -------
          Content Direction: LeftToRight


             🔴 Border
             ==========
             Available Space: (Width: 82,567, Height: 427,300)
             Space Plan: Wrap
             ----------
             Color: #BDBDBD
             Top: 0,5
             Right: 0,5
             Bottom: 0,5
             Left: 0,5


                🔴 Background
                ==============
                Available Space: (Width: 82,567, Height: 427,300)
                Space Plan: Wrap
                --------------
                Color: #F5F5F5


                   🔴 Padding
                   ===========
                   Available Space: (Width: 82,567, Height: 427,300)
                   Space Plan: Wrap
                   -----------
                   Top: 5
                   Right: 5
                   Bottom: 5
                   Left: 5


                      🔴 ShowEntire
                      ==============
                      Available Space: (Width: 72,567, Height: 417,300)
                      Space Plan: Wrap
                      --------------


                         🟡 Constrained
                         ===============
                         Available Space: (Width: 72,567, Height: 417,300)
                         Space Plan: PartialRender (Width: 5,000, Height: 15,000)
                         ---------------
                         Content Direction: LeftToRight
                         Min Width: 5
                         Max Width: 5
                         Min Height: 15
                         Max Height: 15


                            🟡 TextBlock
                            =============
                            Available Space: (Width: 5,000, Height: 15,000)
                            Space Plan: PartialRender (Width: 5,000, Height: 12,000)
                            -------------
                            Content Direction: LeftToRight
                            Alignment: -
                            Line Clamp: -
                            Line Clamp Ellipsis: -
                            Paragraph Spacing: 0
                            Paragraph First Line Indentation: 0
                            Text: Date


             🟢 Border
             ==========
             Available Space: (Width: 165,133, Height: 427,300)
             Space Plan: FullRender (Width: 93,700, Height: 22,000)
             ----------
             Color: #BDBDBD
             Top: 0,5
             Right: 0,5
             Bottom: 0,5
             Left: 0,5


                🟢 Background
                ==============
                Available Space: (Width: 165,133, Height: 427,300)
                Space Plan: FullRender (Width: 93,700, Height: 22,000)
                --------------
                Color: #FFFFFF


                   🟢 Padding
                   ===========
                   Available Space: (Width: 165,133, Height: 427,300)
                   Space Plan: FullRender (Width: 93,700, Height: 22,000)
                   -----------
                   Top: 5
                   Right: 5
                   Bottom: 5
                   Left: 5


                      🟢 TextBlock
                      =============
                      Available Space: (Width: 155,133, Height: 417,300)
                      Space Plan: FullRender (Width: 83,700, Height: 12,000)
                      -------------
                      Content Direction: LeftToRight
                      Alignment: -
                      Line Clamp: -
                      Line Clamp Ellipsis: -
                      Paragraph Spacing: 0
                      Paragraph First Line Indentation: 0
                      Text: 28/03/2024 18:09


             🟢 Border
             ==========
             Available Space: (Width: 82,567, Height: 427,300)
             Space Plan: FullRender (Width: 47,530, Height: 22,000)
             ----------
             Color: #BDBDBD
             Top: 0,5
             Right: 0,5
             Bottom: 0,5
             Left: 0,5


                🟢 Background
                ==============
                Available Space: (Width: 82,567, Height: 427,300)
                Space Plan: FullRender (Width: 47,530, Height: 22,000)
                --------------
                Color: #F5F5F5


                   🟢 Padding
                   ===========
                   Available Space: (Width: 82,567, Height: 427,300)
                   Space Plan: FullRender (Width: 47,530, Height: 22,000)
                   -----------
                   Top: 5
                   Right: 5
                   Bottom: 5
                   Left: 5


                      🟢 TextBlock
                      =============
                      Available Space: (Width: 72,567, Height: 417,300)
                      Space Plan: FullRender (Width: 37,530, Height: 12,000)
                      -------------
                      Content Direction: LeftToRight
                      Alignment: -
                      Line Clamp: -
                      Line Clamp Ellipsis: -
                      Paragraph Spacing: 0
                      Paragraph First Line Indentation: 0
                      Text: Location


             🟢 Border
             ==========
             Available Space: (Width: 165,133, Height: 427,300)
             Space Plan: FullRender (Width: 140,485, Height: 22,000)
             ----------
             Color: #BDBDBD
             Top: 0,5
             Right: 0,5
             Bottom: 0,5
             Left: 0,5


                🟢 Background
                ==============
                Available Space: (Width: 165,133, Height: 427,300)
                Space Plan: FullRender (Width: 140,485, Height: 22,000)
                --------------
                Color: #FFFFFF


                   🟢 Padding
                   ===========
                   Available Space: (Width: 165,133, Height: 427,300)
                   Space Plan: FullRender (Width: 140,485, Height: 22,000)
                   -----------
                   Top: 5
                   Right: 5
                   Bottom: 5
                   Left: 5


                      🟢 TextBlock
                      =============
                      Available Space: (Width: 155,133, Height: 417,300)
                      Space Plan: FullRender (Width: 130,485, Height: 12,000)
                      -------------
                      Content Direction: LeftToRight
                      Alignment: -
                      Line Clamp: -
                      Line Clamp Ellipsis: -
                      Paragraph Spacing: 0
                      Paragraph First Line Indentation: 0
                      Text: 17,67324° N   124,44973° W
```

And the layout bug is as follows:


```csharp
void PhotoDetails(IContainer container)
{
    container.ShowEntire().Border(0.75f).BorderColor(Colors.Grey.Medium).Grid(grid =>
    {
        grid.Columns(6);

        grid.Item().LabelCell().ShowEntire().Width(5).Height(15).Text("Date"); // <- here
        grid.Item(2).ValueCell().Text(Model.Date?.ToString("g") ?? string.Empty);
        grid.Item().LabelCell().Text("Location");
        grid.Item(2).ValueCell().Text(Model.Location.Format());
        
        grid.Item().LabelCell().Text("Comments");
        grid.Item(5).ValueCell().Text(Model.Comments);
    });
}
```

In the future, I would like to also include the reason of why the `Wrap` has happened.

**Comment by ItzSimplyJoe** [comment]
I'm also experiencing this issue.
I've tried with both `EnableDebugging` On and Off and it just seems to hang both times.
Its definitely related to the issue that used to throw this message:
![image](https://github.com/QuestPDF/QuestPDF/assets/111541025/34a47127-bbf8-4211-8ed7-aa9d11239c06)

As the work around for this also fixes the hang, but I need it to throw the error to tell the user that said error has occurred.

**Comment by MarcinZiabek** [comment]
@ItzSimplyJoe 

Have you tried the latest 2024.6.0 version? 
Do you still experience the hanging issue? 
Do you use dynamic image generation? (the `Image()` API overload that provides available space size as an argument)
Could you please create a minimal example that would help me reproduce the problem?

**Comment by ItzSimplyJoe** [comment]
Hi,
Yeh we are using the 2024.6.0 version.
I am still experiencing the issue.
I think we do, however the section that is causing the crash doesn't use an image.

Im not too sure how to re-create it annoyingly. It just happens now and then, the fix we have is to push the content to the next page, and for some reason this fixes the issue.

**Comment by MarcinZiabek** [comment]
@ItzSimplyJoe Could you please share your layout code with me via `contact@questpdf.com`? I am only interested in the section that causes the issue.

**Comment by MarcinZiabek** [comment]
I have made several changes to the layout issue detection algorithm. It works significantly faster and should provide more accurate results. Could you please test the `2024.6.1` version?

**Comment by ItzSimplyJoe** [comment]
Hi,
Sorry for the delayed response.
To attempt to try to provide some more context, I work alongside @girlpunk. 

The issue does still seem to occur, however annoyingly not too sure how to go about doing this as it only happens on certain documents, I'm not too sure where the issue is caused from, and the only report that I have with the issue in contains client data.

On the older versions of QuestPDF it used to throw 
![image](https://github.com/QuestPDF/QuestPDF/assets/111541025/d8cc477e-0708-4abb-b950-42fb8b6ea131)
But now on the newer versions it just seems to hang.

**Comment by MarcinZiabek** [comment]
@ItzSimplyJoe Thank you so much for testing, I highly appreciate your help. Just to make sure, have you tested on at least the 2024.6.1 version? It would be best to use the latest.

**Comment by ItzSimplyJoe** [comment]
Yeh I used 2024.6.4, and it still has the same outcome

**Comment by MarcinZiabek** [comment]
OK, in such a case, I would like to explore a completely different path.

Please check if the problem persists when the `Settings.EnableDebugging` is set to `false`? 

`If the program hangs` - we have an interesting issue related to layouts that do not have any apparent conflicting size constraints but produce infinite documents. It could be a rare corner case or a bug (e.g., precision of floating-point numbers).

If this is the case, could you please comment out various document structures? Maybe we can find a layout structure causing the root cause. I suggest commenting out content starting from the end of the document.

Could you confirm if your document has more complex layout structures, such as DynamicComponent? 
---

`If the program correctly throws an exception` - we have an issue with the logic that attempts to detect the issue location.

**Comment by ItzSimplyJoe** [comment]
Hi,
I tested with `Settings.EnableDebugging`

When it is set to false, after around 5 mins of waiting this error is thrown:
![image](https://github.com/QuestPDF/QuestPDF/assets/111541025/f4928d52-f956-4e68-94b4-fe4a43efce9e)
However when it is set to true, it hangs.

**Comment by MarcinZiabek** [comment]
I appreciate your patience, yet there are more questions 😄 

- Is the 5-minute generation time typical for your documents? What is the average rough generation time? A couple of seconds, a dozen seconds, a minute...?
- Are your documents exceptionally long (thousands of pages)?
- Contain a lot of media (thousands of images) or text element instances (hundreds of thousands)?
- Do you generate any dynamic images or dynamic SVGs?
- Do you use any SkiaSharp integrations that may require rasterization in newer versions of QuestPDF?

Could you please profile a typical document that generates successfully and the problematic report? I suggest using dotTrace with the sampling profiling option enabled. Can you share the results here or via contact@questpdf.com?

The layout debugging algorithm may require additional time to detect the issue, which could make it unproportionally longer than simple document generation. Even if the relation is linear, it can easily take 20-30 minutes.

**Comment by girlpunk** [comment]
Thanks for the help on this one Marcin, wouldn't surprise me if we're chasing the same problem from months ago.
To answer your questions;
- Average time is around a dozen seconds for my test documents, though real documents are often quicker
- Documents average 50-100 pages, maybe 200 at most
- Maybe a dozen images in total, though a logo is repeated on every page. Probably a fair amount of text by your standards, but probably not in the hundreds of thousands
- 2 dynamically generated graphs
- No integrations beyond the graphs

**Comment by MarcinZiabek** [comment]
I also expect that the data for the problematic report is close to typical? Is there anything unusual regarding the amount of content, complexity of graphs, etc.?

I think that the profiling session may help us a lot 😄

**Comment by girlpunk** [comment]
I don't _think_ so, fairly standard mix of text and basic layout elements, the charts are simple bar charts with about 5 bars each.

I believe Joe is getting set up with dotTrace now to generate a profile report for you

**Comment by ItzSimplyJoe** [comment]
@MarcinZiabek 
Ive got the 2 profile reports, however one of the documents I used to generate the report contained client data.
Do you know if the dotTrace report will contain any of that data?

**Comment by MarcinZiabek** [comment]
As far as I know, dotTrace collects only code-related runtime metrics. I have never seen reports that include data/state.

**Comment by ItzSimplyJoe** [comment]
Ok, I have sent the files to you via email

**Comment by MarcinZiabek** [comment]
Thank you for sending both files. Unfortunately, I don't see anything interesting in particular. The generation cost is typically distributed, meaning most of the time is spent on text-related calculations. 

1) Could you please share a typical PDF report with me so I can learn more about its layout structure?
2) Could you please start removing content from the document piece by piece (I suggest starting from the end), and observe if any particular document section introduces the performance issue?

**Comment by ItzSimplyJoe** [comment]
Hi,
My apologies for the slow response.
Attached below is a stack trace that may help.

```System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at QuestPDF.Drawing.DocumentGenerator.<RenderPass>g__ThrowLayoutException|11_2[TCanvas](<>c__DisplayClass11_0`1& )
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, ContainerElement content)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(SkWriteStream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
   at Scribe.Pages.Editor.<>c__DisplayClass0_0.<<DownloadPreviewAsync>b__1>d.MoveNext() in C:\Users\JoeBostock\source\repos\Scribe\Scribe\Pages\Editor.export.razor.cs:line 50
 ```

**Comment by ItzSimplyJoe** [comment]
Hi Marcin,

Its been a while.
We may have found the cause for this issue.

We have found that it occurs when there is an `IContainer` with `EnsureSpace` applied with a column as the container.
Then within the column have multiple items in succession that contain a `PageBreak`.

By removing `EnsureSpace` We seem to have resolved the issue.

Hope this helps

**Comment by MarcinZiabek** [comment]
@ItzSimplyJoe Wow! It sounds amazing! Thank you so much for your dedication and finding the root cause.

It is not on my side to investigate the root cause and apply necessary fixes.

**Comment by MarcinZiabek** [comment]
This issue appears to be successfully resolved! 🎉

Additionally, in the 2025.1.4 release, I have updated the behavior of the EnsureSpace element to prevent any layout rendering issues.

This version also introduces the PreventPageBreak API, which is likely the solution you’ve been looking for from the very beginning. You can find more details here: [Prevent Page Break API](https://www.questpdf.com/api-reference/prevent-page-break.html). Hope this helps!

As there has been no further activity, I’m closing this issue. If you have a similar request in the future, please feel free to open a new GitHub issue. I truly appreciate your feedback! ❤️
