### ISSUE TITLE
Can not display barcode font

### ISSUE THREAD

**Issue by sasaPantic** [QuestPDF/QuestPDF#809]
Can you check why custom barcode file can not be loaded, please?
I am using attached Code39.ttf. Also I tried all steps described at https://www.questpdf.com/going-production/font-management.html but it throws exception.
Thanks
[Code39.zip](https://github.com/QuestPDF/QuestPDF/files/14515327/Code39.zip)

**Comment by girlpunk** [comment]
Hi,

Please could you include full details of the code you are trying to run, and any exceptions including full messages and stack traces.

Thank you

**Comment by sasaPantic** [comment]
Hi, 
This is my code:
In Program.cs
`FontManager.RegisterFont(File.OpenRead(@"C:\hard-coded-path\Code39.ttf"));
`
And in separate project where I create pdf:
```
column.Item().Text(text =>
{
    text.Span("Email: ").SemiBold();
    text.Span($"{model.Client.Address.Email}");
});

column.Item().Text(text =>
{
    text.Span($"{model.OrderNumber}").FontFamily("Code39");
}); 
```

And here is the exception:
```
Error Messsage: 
System.ArgumentException: The typeface 'Code39' could not be found. Please consider the following options: 
1) install the font on your operating system or execution environment. 
2) load a font file specifically for QuestPDF usage via the QuestPDF.Drawing.FontManager.RegisterFontType(Stream fileContentStream) static method. 
Available font family names: [IDAutomationHC39M, Cascadia Code, Cascadia Mono, Arial, Bahnschrift, Calibri, Cambria, Cambria Math, Candara, Comic Sans MS, Consolas, 
Constantia, Corbel, Courier New, Ebrima, Franklin Gothic, Gabriola, Gadugi, Georgia, Impact, Ink Free, Javanese Text, Leelawadee UI, Lucida Console, Lucida Sans Unicode, 
Malgun Gothic, Microsoft Himalaya, Microsoft JhengHei, Microsoft JhengHei UI, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft Sans Serif, Microsoft Tai Le, Microsoft YaHei, 
Microsoft YaHei UI, Microsoft Yi Baiti, MingLiU-ExtB, PMingLiU-ExtB, MingLiU_HKSCS-ExtB, Mongolian Baiti, MS Gothic, MS UI Gothic, MS PGothic, MV Boli, Myanmar Text, Nirmala UI, 
Palatino Linotype, Sans Serif Collection, Segoe Fluent Icons, Segoe MDL2 Assets, Segoe Print, Segoe Script, Segoe UI, Segoe UI Emoji, Segoe UI Historic, Segoe UI Symbol, Segoe UI Variable Small, 
Segoe UI Variable Text, Segoe UI Variable Display, SimSun, NSimSun, SimSun-ExtB, Sitka Small, Sitka Text, Sitka Subheading, Sitka Heading, Sitka Display, Sitka Banner, Sylfaen, Symbol, Tahoma, Times New Roman, Trebuchet MS, 
Verdana, Webdings, Wingdings, Yu Gothic, Yu Gothic UI, HoloLens MDL2 Assets, Book Antiqua, Bookman Old Style, Bradley Hand ITC, Bookshelf Symbol 7, Century, Freestyle Script, French Script MT, Garamond, Century Gothic, 
Kristen ITC, Juice ITC, Leelawadee, Lucida Handwriting, Mistral, Microsoft Uighur, Monotype Corsiva, MS Outlook, Papyrus, Pristina, MS Reference Sans Serif, MS Reference Specialty, Tempus Sans ITC, Wingdings 2, Wingdings 3, 
MT Extra, BarCode, Marlett]
   
   at QuestPDF.Drawing.FontManager.<ToPaint>g__GetTypeface|15_1(TextStyle style)
   at QuestPDF.Drawing.FontManager.<ToPaint>g__Convert|15_0(TextStyle style)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at QuestPDF.Drawing.FontManager.ToPaint(TextStyle style)
   at QuestPDF.Drawing.FontManager.<>c.<ToFont>b__19_0(TextStyle key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at QuestPDF.Drawing.FontManager.ToFont(TextStyle style)
   at QuestPDF.Elements.Text.FontFallback.<<SplitWithFontFallback>g__GetFallbackOptions|4_0>d.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at QuestPDF.Elements.Text.FontFallback.<SplitWithFontFallback>d__4.MoveNext()
   at QuestPDF.Elements.Text.FontFallback.<ApplyFontFallback>d__5.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ques

Target Method: 
SkiaSharp.SKTypeface <ToPaint>g__GetTypeface|15_1(QuestPDF.Infrastructure.TextStyle)
```
Thanks in advance

**Comment by girlpunk** [comment]
Is Code39 the name of the font? Note that the name of the font isn't necessarily the same as the filename, an in your case may well be "Code 39" or similar. If you're unable to find the name from the ttf file, there's an overload of RegisterFont available that lets you set the name explicitly.

**Comment by sasaPantic** [comment]
Hello @girlpunk 
I run the script that displays font name and it is Code39. So it is obviously an issue with the font name and I found that is very difficult to find font name.
Anyway, I managed to display barcode with `RegisterFontWithCustomName` instead  `RegisterFont` method.
Thank you very much for your support!

**Comment by siyuduan2023** [comment]
> Hello @girlpunk I run the script that displays font name and it is Code39. So it is obviously an issue with the font name and I found that is very difficult to find font name. Anyway, I managed to display barcode with `RegisterFontWithCustomName` instead `RegisterFont` method. Thank you very much for your support!

Thank you! I tried to implement a customed font using RegisterFont method at the beginning, it didn't work. And tried your way using RegisterFontWithCustomName method, it works!
