### ISSUE TITLE
Unable to find an entry point named 'svg_get_size' in DLL 'QuestPdfSkia'

### ISSUE THREAD

**Issue by alex-kukhtin** [QuestPDF/QuestPDF#870]
**Problem description**
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'svg_get_size' in DLL 'QuestPdfSkia'.
   at QuestPDF.Skia.SkSvgImage.API.svg_get_size(IntPtr svg, SkSvgImageSize& size, SkRect& viewBox)
   at QuestPDF.Skia.SkSvgImage..ctor(String svgString, SkFontManager fontManager)
   at QuestPDF.Infrastructure.SvgImage..ctor(String content)
   at QuestPDF.Infrastructure.SvgImage.FromText(String svg)

**To Reproduce**
```csharp
var svgImage = SvgImage.FromText("<svg></svg>");
```

**Environment**
- QuestPDF 2024.3.2
- .NET Framework 4.8
- Windows 11 win-x64

**Comment by alex-kukhtin** [comment]
By the way. In version 2024.3.1 it works correctly.

**Comment by MarcinZiabek** [comment]
Would you please try the `2024.3.4` version?

**Comment by alex-kukhtin** [comment]
Yes. It works. Thank you.
I've already closed the issue.
