### ISSUE TITLE
QuestPDF.Settings throwing an exception

### ISSUE THREAD

**Issue by troika-support** [QuestPDF/QuestPDF#947]
I am developing a .NET 8 Blazor Hosted application. On trying to run the solution, it's giving me an error on startup. When I do an inspect in my browser, it shows me the following error:

Error: One or more errors occurred. (The type initializer for 'QuestPDF.Settings' threw an exception.)
    at Jn (marshal-to-js.ts:349:18)
    at Tl (marshal-to-js.ts:306:28)
    at do_icall (05863202:0x52e9b6)
    at do_icall_wrapper (05863202:0x52992a)
    at mono_interp_exec_method (05863202:0x51b858)
    at interp_entry (05863202:0x52cd4e)
    at interp_entry_static_0 (05863202:0x52d812)
    at wasm_native_to_interp_System_Private_CoreLib_ThreadPool_BackgroundJobHandler (05863202:0x7d3684)
    at mono_background_exec (05863202:0x55f015)
    at e.<computed> (cwraps.ts:338:24)

This error shows when I add the following code in the Program.cs:

QuestPDF.Settings.License = LicenseType.Community;

When I remove or comment out the line of code I won't bump into the error. However the documents within the app won't show as a result of not having the license type registered.

What I want is to have the error disappear, I have 2 solutions which I used QuestPDF and didn't give this issue

I installed version 2023.12.6
I'm developing in Visual Studio 2022 version 17.10.3, running on Windows 11 Pro, x64 bit

**Comment by danirzv** [comment]
I'm not sure how will it go on if you trying to use pdf generator on Blazor client side!
but if you are doing Server/Client Blazor your server logging mechanism will give us so much more info to point out the issue

**Comment by MarcinZiabek** [comment]
Indeed, the exception contains significantly more information and details about available options and the root cause. To use the 2023.12.X version in Blazor, you must install the necessary WASM-related packages for SkiaSharp and HarfBuzzSharp. 

Although the above is possible, I recommend using the latest 2024.7.X version and running it on the server side.

**Comment by MarcinZiabek** [comment]
Since there has been no recent activity, I’m closing this issue. If you experience a similar problem or have a related request, feel free to open a new GitHub issue. I appreciate your feedback! ❤️

**Comment by tipaz** [comment]
Hi @MarcinZiabek 

I am getting the same error i am using version 2026.2.4, with vs studio.

I installed the nuget version, is there anything else i need to do?
