### ISSUE TITLE
"Your runtime is currently not supported by QuestPDF." on AWS 64bit Amazon Linux

### ISSUE THREAD

**Issue by jerschneid** [QuestPDF/QuestPDF#969]
### Discussed in https://github.com/QuestPDF/QuestPDF/discussions/966

<div type='discussions-op-text'>

<sup>Originally posted by **jerschneid** July 31, 2024</sup>
Hi QuestPDF Community!

I'm using QuestPDF and it works successfully locally (MacOS, .NET Core 7.0). When I deploy to AWS Elastic Beanstalk with this platform:

`.NET Core running on 64bit Amazon Linux 2/2.8.0`

I get this error below. I've seen a couple discussions around related issues, but haven't been able to resolve this. I tried installing the latest stable (2.88.8) and preview (3.0.0-preview.4.1) versions of `SkiaSharp.NativeAssets.Linux.NoDependencies`, but they all still throw the error. Any help would be greatly appreciated!

The error in question.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'QuestPDF.Settings' threw an exception.
 ---> System.Exception: The QuestPDF library has encountered an issue while loading one of its dependencies.
 Your runtime is currently not supported by QuestPDF. Currently supported runtimes are: win-x86, win-x64, linux-x64, linux-arm64, linux-musl-x64, osx-x64, osx-arm64.
 It appears that your current operating system distribution may be outdated. For optimal compatibility, please consider updating it to a more recent version.
 ---> System.DllNotFoundException: Unable to load shared library 'QuestPdfSkia' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
 /var/app/current/QuestPdfSkia.so: cannot open shared object file: No such file or directory
 /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /var/app/current/libQuestPdfSkia.so)
 libQuestPdfSkia.so: cannot open shared object file: No such file or directory
 /var/app/current/QuestPdfSkia: cannot open shared object file: No such file or directory
 /var/app/current/libQuestPdfSkia: cannot open shared object file: No such file or directory
 at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.API.check_compatibility_by_calculating_sum(Int32 a, Int32 b)
 at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.CheckIfExceptionIsThrownWhenLoadingNativeDependencies()
 --- End of inner exception stack trace ---
 at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.<Test>g__ThrowCompatibilityException|1_0(Exception innerException)
 at QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.Test()
 at QuestPDF.Helpers.NativeDependencyCompatibilityChecker.Test()
 at QuestPDF.Settings..cctor()
 --- End of inner exception stack trace ---
 at QuestPDF.Settings.set_License(Nullable`1 value)
```</div>

**Comment by MarcinZiabek** [comment]
Unfortunately, Amazon has chosen a quite old Linux distribution as a default for the dotnet 7 docker image. Could you please update to the dotnet 8 version?

**Comment by thecartermatt** [comment]
Is there a plan to address this? I am looking for amazon linux support as well.

**Comment by MarcinZiabek** [comment]
Since there has been no recent activity, I’m closing this issue. If you have a similar request in the future, please feel free to open a new GitHub issue. Thanks for your feedback! ❤️
