### ISSUE TITLE
TypeInitializationException when instantiating QuestPDF from a Windows Service application on a Windows Server.

### ISSUE THREAD

**Issue by bjorn-malmo** [QuestPDF/QuestPDF#981]
**Describe the bug**
When rendering a pdf, a TypeInitializationException is immediately thrown. 

It appears it is trying to locate a file somewhere, and it ends up in the Windows\System32 folder. If a folder named x64 does not exist in this path, the exception is thrown and nothing works.

However, if the folder C:\WINDOWS\system32\x64 does exist, even if empty with only read access, everything works perfectly.
I expect this is caused by the fact that the process running with minimal privileges and maybe the path or working directory 
defaults to C:\WINDOWS\system32\.

It is probably a quick fix (if you know where to look) to just check if the folder exists, or try/catch the error.

Full stack trace:
Exception TypeInitializationException: The type initializer for 'QuestPDF.Drawing.FontManager' threw an exception.
Inner exception (1) DirectoryNotFoundException: Could not find a part of the path 'C:\WINDOWS\system32\x64'.
--- StackTrace ---
   at QuestPDF.Drawing.FontManager.get_TypefaceProvider()
   at QuestPDF.Elements.Text.SkParagraphBuilderPoolManager.Get(ParagraphStyleConfiguration configuration)
   at QuestPDF.Elements.Text.TextBlock.BuildParagraph()
   at QuestPDF.Elements.Text.TextBlock.Initialize()
   at QuestPDF.Elements.Text.TextBlock.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Elements.Row.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Row.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Column.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Column.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.Proxy.SnapshotRecorder.Measure(Size availableSpace)
   at QuestPDF.Elements.Decoration.<PlanLayout>g__GetDecorationMeasurement|20_0(Element element, <>c__DisplayClass20_0& )
   at QuestPDF.Elements.Decoration.PlanLayout(Size availableSpace)
   at QuestPDF.Elements.Decoration.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Padding.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Constrained.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Elements.Layers.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Infrastructure.ContainerElement.Measure(Size availableSpace)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, ContainerElement content)
   at QuestPDF.Drawing.DocumentGenerator.RenderSingleDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document, DocumentSettings settings)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at VidiView.Reporting.Render.StudyReportDocument.<>c__DisplayClass47_0.<SaveAsAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidiView.Reporting.Render.StudyReportDocument.<SaveAsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidiView.Server.Workflow.ExportQueue.ConvertReportToPdfTask.<ConvertAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidiView.Server.Workflow.ExportQueue.ExportQueueItem.<ExecuteTask>d__28.MoveNext()

**Environment**
QuestPDF 2024.7.3
.NET Framework 4.8 (x64)
Windows Server 2019

**Comment by bjorn-malmo** [comment]
I've located the exception to the FontDiscoveryPaths being initialized to ApplicationFilesPath. Since Directory.EnumerateFiles throws for non-existent path, this is a dangerous construct to call in a static constructor.
In my specific case, running as a Windows Service, the working directory is by default Windows\system32 and since this path does not contain an x64 folder, the library won't load. 

I'm not sure why the font discovery path is initialized like this, since font files probably exists elsewhere (not in an x64 folder) .

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by shahabganji** [comment]
Any updates on this, we have similar issue on a WindowsServer machine but not on Mac!

**Comment by MarcinZiabek** [comment]
Apologies for the very long delay in responding — I'm currently going through older issues in the backlog.

The original issue was fixed in QuestPDF 2024.10.1, which improved the default font-discovery path and safely handled missing or inaccessible directories. Font discovery and application-path resolution were further hardened in QuestPDF 2026.7.0.

I'm closing this issue as resolved. If it still occurs on a current version, please reopen it and I'll take another look.
